declare interface alm_asset {
      acquisition_method: GlideElement<alm_asset, glideElementType.defaultType>;
active_to: GlideElement<alm_asset, glideElementType.g_boolean>;
asset_tag: GlideElement<alm_asset, glideElementType.defaultType>;
assigned: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
assigned_to: GlideElement<alm_asset, glideElementType.g_reference<sys_user>>;
beneficiary: GlideElement<alm_asset, glideElementType.g_reference<core_company>>;
checked_in: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
checked_out: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
ci: GlideElement<alm_asset, glideElementType.g_reference<cmdb_ci>>;
comments: GlideElement<alm_asset, glideElementType.defaultType>;
company: GlideElement<alm_asset, glideElementType.g_reference<core_company>>;
cost: GlideElement<alm_asset, glideElementType.g_currency>;
cost_center: GlideElement<alm_asset, glideElementType.g_reference<cmn_cost_center>>;
delivery_date: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
department: GlideElement<alm_asset, glideElementType.g_reference<cmn_department>>;
depreciated_amount: GlideElement<alm_asset, glideElementType.g_currency>;
depreciation: GlideElement<alm_asset, glideElementType.g_reference<cmdb_depreciation>>;
depreciation_date: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
display_name: GlideElement<alm_asset, glideElementType.defaultType>;
disposal_reason: GlideElement<alm_asset, glideElementType.defaultType>;
due: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
due_in: GlideElement<alm_asset, glideElementType.defaultType>;
expenditure_type: GlideElement<alm_asset, glideElementType.defaultType>;
gl_account: GlideElement<alm_asset, glideElementType.defaultType>;
install_date: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
install_status: GlideElement<alm_asset, glideElementType.defaultType>;
invoice_number: GlideElement<alm_asset, glideElementType.defaultType>;
justification: GlideElement<alm_asset, glideElementType.defaultType>;
lease_id: GlideElement<alm_asset, glideElementType.defaultType>;
location: GlideElement<alm_asset, glideElementType.g_reference<cmn_location>>;
managed_by: GlideElement<alm_asset, glideElementType.g_reference<sys_user>>;
model: GlideElement<alm_asset, glideElementType.g_reference<cmdb_model>>;
model_category: GlideElement<alm_asset, glideElementType.g_reference<cmdb_model_category>>;
old_status: GlideElement<alm_asset, glideElementType.defaultType>;
old_substatus: GlideElement<alm_asset, glideElementType.defaultType>;
order_date: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
owned_by: GlideElement<alm_asset, glideElementType.g_reference<sys_user>>;
parent: GlideElement<alm_asset, glideElementType.g_reference<alm_asset>>;
po_number: GlideElement<alm_asset, glideElementType.defaultType>;
pre_allocated: GlideElement<alm_asset, glideElementType.g_boolean>;
purchase_date: GlideElement<alm_asset, glideElementType.g_glide_date>;
quantity: GlideElement<alm_asset, glideElementType.defaultType>;
request_line: GlideElement<alm_asset, glideElementType.g_reference<sc_req_item>>;
resale_price: GlideElement<alm_asset, glideElementType.g_price>;
reserved_for: GlideElement<alm_asset, glideElementType.g_reference<sys_user>>;
residual: GlideElement<alm_asset, glideElementType.g_currency>;
residual_date: GlideElement<alm_asset, glideElementType.g_glide_date>;
retired: GlideElement<alm_asset, glideElementType.g_glide_date>;
retirement_date: GlideElement<alm_asset, glideElementType.g_glide_date>;
salvage_value: GlideElement<alm_asset, glideElementType.g_currency>;
serial_number: GlideElement<alm_asset, glideElementType.defaultType>;
skip_sync: GlideElement<alm_asset, glideElementType.g_boolean>;
stockroom: GlideElement<alm_asset, glideElementType.g_reference<alm_stockroom>>;
substatus: GlideElement<alm_asset, glideElementType.defaultType>;
supported_by: GlideElement<alm_asset, glideElementType.g_reference<sys_user>>;
support_group: GlideElement<alm_asset, glideElementType.g_reference<sys_user_group>>;
sys_class_name: GlideElement<alm_asset, glideElementType.defaultType>;
sys_created_by: GlideElement<alm_asset, glideElementType.defaultType>;
sys_created_on: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
sys_domain: GlideElement<alm_asset, glideElementType.defaultType>;
sys_domain_path: GlideElement<alm_asset, glideElementType.defaultType>;
sys_id: GlideElement<alm_asset, glideElementType.defaultType>;
sys_mod_count: GlideElement<alm_asset, glideElementType.defaultType>;
sys_updated_by: GlideElement<alm_asset, glideElementType.defaultType>;
sys_updated_on: GlideElement<alm_asset, glideElementType.g_glide_date_time>;
vendor: GlideElement<alm_asset, glideElementType.g_reference<core_company>>;
warranty_expiration: GlideElement<alm_asset, glideElementType.g_glide_date>;
work_notes: GlideElement<alm_asset, glideElementType.defaultType>;
      _referenceKeys: never | {
        "assigned_to.accumulated_roles": string
"assigned_to.active": string
"assigned_to.avatar": string
"assigned_to.building": string
"assigned_to.calendar_integration": string
"assigned_to.city": string
"assigned_to.company": string
"assigned_to.cost_center": string
"assigned_to.country": string
"assigned_to.date_format": string
"assigned_to.default_perspective": string
"assigned_to.department": string
"assigned_to.email": string
"assigned_to.employee_number": string
"assigned_to.enable_multifactor_authn": string
"assigned_to.failed_attempts": string
"assigned_to.first_name": string
"assigned_to.gender": string
"assigned_to.home_phone": string
"assigned_to.internal_integration_user": string
"assigned_to.introduction": string
"assigned_to.last_login": string
"assigned_to.last_login_time": string
"assigned_to.last_name": string
"assigned_to.ldap_server": string
"assigned_to.location": string
"assigned_to.locked_out": string
"assigned_to.manager": string
"assigned_to.middle_name": string
"assigned_to.mobile_phone": string
"assigned_to.name": string
"assigned_to.notification": string
"assigned_to.password_needs_reset": string
"assigned_to.phone": string
"assigned_to.photo": string
"assigned_to.preferred_language": string
"assigned_to.roles": string
"assigned_to.schedule": string
"assigned_to.source": string
"assigned_to.state": string
"assigned_to.street": string
"assigned_to.sys_class_name": string
"assigned_to.sys_created_by": string
"assigned_to.sys_created_on": string
"assigned_to.sys_domain": string
"assigned_to.sys_domain_path": string
"assigned_to.sys_id": string
"assigned_to.sys_mod_count": string
"assigned_to.sys_updated_by": string
"assigned_to.sys_updated_on": string
"assigned_to.time_format": string
"assigned_to.time_zone": string
"assigned_to.title": string
"assigned_to.user_name": string
"assigned_to.user_password": string
"assigned_to.vip": string
"assigned_to.web_service_access_only": string
"assigned_to.zip": string
"beneficiary.apple_icon": string
"beneficiary.banner_image": string
"beneficiary.banner_image_light": string
"beneficiary.banner_text": string
"beneficiary.city": string
"beneficiary.contact": string
"beneficiary.country": string
"beneficiary.customer": string
"beneficiary.discount": string
"beneficiary.fax_phone": string
"beneficiary.fiscal_year": string
"beneficiary.latitude": string
"beneficiary.lat_long_error": string
"beneficiary.longitude": string
"beneficiary.manufacturer": string
"beneficiary.market_cap": string
"beneficiary.name": string
"beneficiary.notes": string
"beneficiary.num_employees": string
"beneficiary.parent": string
"beneficiary.phone": string
"beneficiary.primary": string
"beneficiary.profits": string
"beneficiary.publicly_traded": string
"beneficiary.rank_tier": string
"beneficiary.revenue_per_year": string
"beneficiary.state": string
"beneficiary.stock_price": string
"beneficiary.stock_symbol": string
"beneficiary.street": string
"beneficiary.sys_class_name": string
"beneficiary.sys_created_by": string
"beneficiary.sys_created_on": string
"beneficiary.sys_id": string
"beneficiary.sys_mod_count": string
"beneficiary.sys_updated_by": string
"beneficiary.sys_updated_on": string
"beneficiary.theme": string
"beneficiary.vendor": string
"beneficiary.vendor_manager": string
"beneficiary.vendor_type": string
"beneficiary.website": string
"beneficiary.zip": string
"ci.asset": string
"ci.asset_tag": string
"ci.assigned": string
"ci.assigned_to": string
"ci.assignment_group": string
"ci.attributes": string
"ci.can_print": string
"ci.category": string
"ci.change_control": string
"ci.checked_in": string
"ci.checked_out": string
"ci.comments": string
"ci.company": string
"ci.correlation_id": string
"ci.cost": string
"ci.cost_cc": string
"ci.cost_center": string
"ci.delivery_date": string
"ci.department": string
"ci.discovery_source": string
"ci.dns_domain": string
"ci.due": string
"ci.due_in": string
"ci.duplicate_of": string
"ci.fault_count": string
"ci.first_discovered": string
"ci.fqdn": string
"ci.gl_account": string
"ci.install_date": string
"ci.install_status": string
"ci.invoice_number": string
"ci.ip_address": string
"ci.justification": string
"ci.last_discovered": string
"ci.lease_id": string
"ci.location": string
"ci.mac_address": string
"ci.maintenance_schedule": string
"ci.managed_by": string
"ci.manufacturer": string
"ci.model_id": string
"ci.model_number": string
"ci.monitor": string
"ci.name": string
"ci.operational_status": string
"ci.order_date": string
"ci.owned_by": string
"ci.po_number": string
"ci.purchase_date": string
"ci.schedule": string
"ci.serial_number": string
"ci.short_description": string
"ci.skip_sync": string
"ci.start_date": string
"ci.subcategory": string
"ci.supported_by": string
"ci.support_group": string
"ci.sys_class_name": string
"ci.sys_class_path": string
"ci.sys_created_by": string
"ci.sys_created_on": string
"ci.sys_domain": string
"ci.sys_domain_path": string
"ci.sys_id": string
"ci.sys_mod_count": string
"ci.sys_updated_by": string
"ci.sys_updated_on": string
"ci.unverified": string
"ci.vendor": string
"ci.warranty_expiration": string
"company.apple_icon": string
"company.banner_image": string
"company.banner_image_light": string
"company.banner_text": string
"company.city": string
"company.contact": string
"company.country": string
"company.customer": string
"company.discount": string
"company.fax_phone": string
"company.fiscal_year": string
"company.latitude": string
"company.lat_long_error": string
"company.longitude": string
"company.manufacturer": string
"company.market_cap": string
"company.name": string
"company.notes": string
"company.num_employees": string
"company.parent": string
"company.phone": string
"company.primary": string
"company.profits": string
"company.publicly_traded": string
"company.rank_tier": string
"company.revenue_per_year": string
"company.state": string
"company.stock_price": string
"company.stock_symbol": string
"company.street": string
"company.sys_class_name": string
"company.sys_created_by": string
"company.sys_created_on": string
"company.sys_id": string
"company.sys_mod_count": string
"company.sys_updated_by": string
"company.sys_updated_on": string
"company.theme": string
"company.vendor": string
"company.vendor_manager": string
"company.vendor_type": string
"company.website": string
"company.zip": string
"cost_center.account_number": string
"cost_center.code": string
"cost_center.location": string
"cost_center.manager": string
"cost_center.name": string
"cost_center.parent": string
"cost_center.sys_created_by": string
"cost_center.sys_created_on": string
"cost_center.sys_id": string
"cost_center.sys_mod_count": string
"cost_center.sys_updated_by": string
"cost_center.sys_updated_on": string
"cost_center.valid_from": string
"cost_center.valid_to": string
"department.business_unit": string
"department.company": string
"department.cost_center": string
"department.dept_head": string
"department.description": string
"department.head_count": string
"department.id": string
"department.name": string
"department.parent": string
"department.primary_contact": string
"department.sys_created_by": string
"department.sys_created_on": string
"department.sys_id": string
"department.sys_mod_count": string
"department.sys_updated_by": string
"department.sys_updated_on": string
"depreciation.category": string
"depreciation.depreciation_time": string
"depreciation.depreciation_unit": string
"depreciation.name": string
"depreciation.script": string
"depreciation.sys_created_by": string
"depreciation.sys_created_on": string
"depreciation.sys_id": string
"depreciation.sys_mod_count": string
"depreciation.sys_updated_by": string
"depreciation.sys_updated_on": string
"location.city": string
"location.company": string
"location.contact": string
"location.country": string
"location.fax_phone": string
"location.full_name": string
"location.latitude": string
"location.lat_long_error": string
"location.longitude": string
"location.name": string
"location.parent": string
"location.phone": string
"location.phone_territory": string
"location.state": string
"location.stock_room": string
"location.street": string
"location.sys_created_by": string
"location.sys_created_on": string
"location.sys_id": string
"location.sys_mod_count": string
"location.sys_updated_by": string
"location.sys_updated_on": string
"location.time_zone": string
"location.zip": string
"managed_by.accumulated_roles": string
"managed_by.active": string
"managed_by.avatar": string
"managed_by.building": string
"managed_by.calendar_integration": string
"managed_by.city": string
"managed_by.company": string
"managed_by.cost_center": string
"managed_by.country": string
"managed_by.date_format": string
"managed_by.default_perspective": string
"managed_by.department": string
"managed_by.email": string
"managed_by.employee_number": string
"managed_by.enable_multifactor_authn": string
"managed_by.failed_attempts": string
"managed_by.first_name": string
"managed_by.gender": string
"managed_by.home_phone": string
"managed_by.internal_integration_user": string
"managed_by.introduction": string
"managed_by.last_login": string
"managed_by.last_login_time": string
"managed_by.last_name": string
"managed_by.ldap_server": string
"managed_by.location": string
"managed_by.locked_out": string
"managed_by.manager": string
"managed_by.middle_name": string
"managed_by.mobile_phone": string
"managed_by.name": string
"managed_by.notification": string
"managed_by.password_needs_reset": string
"managed_by.phone": string
"managed_by.photo": string
"managed_by.preferred_language": string
"managed_by.roles": string
"managed_by.schedule": string
"managed_by.source": string
"managed_by.state": string
"managed_by.street": string
"managed_by.sys_class_name": string
"managed_by.sys_created_by": string
"managed_by.sys_created_on": string
"managed_by.sys_domain": string
"managed_by.sys_domain_path": string
"managed_by.sys_id": string
"managed_by.sys_mod_count": string
"managed_by.sys_updated_by": string
"managed_by.sys_updated_on": string
"managed_by.time_format": string
"managed_by.time_zone": string
"managed_by.title": string
"managed_by.user_name": string
"managed_by.user_password": string
"managed_by.vip": string
"managed_by.web_service_access_only": string
"managed_by.zip": string
"model.acquisition_method": string
"model.asset_tracking_strategy": string
"model.barcode": string
"model.bundle": string
"model.certified": string
"model.cmdb_ci_class": string
"model.cmdb_model_category": string
"model.comments": string
"model.cost": string
"model.depreciation": string
"model.description": string
"model.display_name": string
"model.expenditure_type": string
"model.flow_rate": string
"model.full_name": string
"model.main_component": string
"model.manufacturer": string
"model.model_number": string
"model.name": string
"model.owner": string
"model.picture": string
"model.power_consumption": string
"model.product_catalog_item": string
"model.rack_units": string
"model.salvage_value": string
"model.short_description": string
"model.sla": string
"model.sound_power": string
"model.status": string
"model.sys_class_name": string
"model.sys_created_by": string
"model.sys_created_on": string
"model.sys_domain": string
"model.sys_domain_path": string
"model.sys_id": string
"model.sys_mod_count": string
"model.sys_updated_by": string
"model.sys_updated_on": string
"model.type": string
"model.weight": string
"model_category.allow_as_master": string
"model_category.allow_in_bundle": string
"model_category.allow_pre_allocation": string
"model_category.asset_class": string
"model_category.bundle": string
"model_category.cmdb_ci_class": string
"model_category.enforce_verification": string
"model_category.name": string
"model_category.sys_created_by": string
"model_category.sys_created_on": string
"model_category.sys_domain": string
"model_category.sys_domain_path": string
"model_category.sys_id": string
"model_category.sys_mod_count": string
"model_category.sys_updated_by": string
"model_category.sys_updated_on": string
"owned_by.accumulated_roles": string
"owned_by.active": string
"owned_by.avatar": string
"owned_by.building": string
"owned_by.calendar_integration": string
"owned_by.city": string
"owned_by.company": string
"owned_by.cost_center": string
"owned_by.country": string
"owned_by.date_format": string
"owned_by.default_perspective": string
"owned_by.department": string
"owned_by.email": string
"owned_by.employee_number": string
"owned_by.enable_multifactor_authn": string
"owned_by.failed_attempts": string
"owned_by.first_name": string
"owned_by.gender": string
"owned_by.home_phone": string
"owned_by.internal_integration_user": string
"owned_by.introduction": string
"owned_by.last_login": string
"owned_by.last_login_time": string
"owned_by.last_name": string
"owned_by.ldap_server": string
"owned_by.location": string
"owned_by.locked_out": string
"owned_by.manager": string
"owned_by.middle_name": string
"owned_by.mobile_phone": string
"owned_by.name": string
"owned_by.notification": string
"owned_by.password_needs_reset": string
"owned_by.phone": string
"owned_by.photo": string
"owned_by.preferred_language": string
"owned_by.roles": string
"owned_by.schedule": string
"owned_by.source": string
"owned_by.state": string
"owned_by.street": string
"owned_by.sys_class_name": string
"owned_by.sys_created_by": string
"owned_by.sys_created_on": string
"owned_by.sys_domain": string
"owned_by.sys_domain_path": string
"owned_by.sys_id": string
"owned_by.sys_mod_count": string
"owned_by.sys_updated_by": string
"owned_by.sys_updated_on": string
"owned_by.time_format": string
"owned_by.time_zone": string
"owned_by.title": string
"owned_by.user_name": string
"owned_by.user_password": string
"owned_by.vip": string
"owned_by.web_service_access_only": string
"owned_by.zip": string
"parent.acquisition_method": string
"parent.active_to": string
"parent.asset_tag": string
"parent.assigned": string
"parent.assigned_to": string
"parent.beneficiary": string
"parent.checked_in": string
"parent.checked_out": string
"parent.ci": string
"parent.comments": string
"parent.company": string
"parent.cost": string
"parent.cost_center": string
"parent.delivery_date": string
"parent.department": string
"parent.depreciated_amount": string
"parent.depreciation": string
"parent.depreciation_date": string
"parent.display_name": string
"parent.disposal_reason": string
"parent.due": string
"parent.due_in": string
"parent.expenditure_type": string
"parent.gl_account": string
"parent.install_date": string
"parent.install_status": string
"parent.invoice_number": string
"parent.justification": string
"parent.lease_id": string
"parent.location": string
"parent.managed_by": string
"parent.model": string
"parent.model_category": string
"parent.old_status": string
"parent.old_substatus": string
"parent.order_date": string
"parent.owned_by": string
"parent.parent": string
"parent.po_number": string
"parent.pre_allocated": string
"parent.purchase_date": string
"parent.quantity": string
"parent.request_line": string
"parent.resale_price": string
"parent.reserved_for": string
"parent.residual": string
"parent.residual_date": string
"parent.retired": string
"parent.retirement_date": string
"parent.salvage_value": string
"parent.serial_number": string
"parent.skip_sync": string
"parent.stockroom": string
"parent.substatus": string
"parent.supported_by": string
"parent.support_group": string
"parent.sys_class_name": string
"parent.sys_created_by": string
"parent.sys_created_on": string
"parent.sys_domain": string
"parent.sys_domain_path": string
"parent.sys_id": string
"parent.sys_mod_count": string
"parent.sys_updated_by": string
"parent.sys_updated_on": string
"parent.vendor": string
"parent.warranty_expiration": string
"parent.work_notes": string
"request_line.backordered": string
"request_line.billable": string
"request_line.cat_item": string
"request_line.configuration_item": string
"request_line.context": string
"request_line.estimated_delivery": string
"request_line.order_guide": string
"request_line.price": string
"request_line.quantity": string
"request_line.recurring_frequency": string
"request_line.recurring_price": string
"request_line.request": string
"request_line.sc_catalog": string
"request_line.stage": string
"request_line.sys_id": string
"request_line.active": string
"request_line.activity_due": string
"request_line.additional_assignee_list": string
"request_line.approval": string
"request_line.approval_history": string
"request_line.approval_set": string
"request_line.assigned_to": string
"request_line.assignment_group": string
"request_line.business_duration": string
"request_line.business_service": string
"request_line.calendar_duration": string
"request_line.closed_at": string
"request_line.closed_by": string
"request_line.close_notes": string
"request_line.cmdb_ci": string
"request_line.comments": string
"request_line.comments_and_work_notes": string
"request_line.company": string
"request_line.contact_type": string
"request_line.contract": string
"request_line.correlation_display": string
"request_line.correlation_id": string
"request_line.delivery_plan": string
"request_line.delivery_task": string
"request_line.description": string
"request_line.due_date": string
"request_line.escalation": string
"request_line.expected_start": string
"request_line.follow_up": string
"request_line.group_list": string
"request_line.impact": string
"request_line.knowledge": string
"request_line.location": string
"request_line.made_sla": string
"request_line.number": string
"request_line.opened_at": string
"request_line.opened_by": string
"request_line.order": string
"request_line.parent": string
"request_line.priority": string
"request_line.reassignment_count": string
"request_line.service_offering": string
"request_line.short_description": string
"request_line.sla_due": string
"request_line.state": string
"request_line.sys_class_name": string
"request_line.sys_created_by": string
"request_line.sys_created_on": string
"request_line.sys_domain": string
"request_line.sys_domain_path": string
"request_line.sys_mod_count": string
"request_line.sys_updated_by": string
"request_line.sys_updated_on": string
"request_line.time_worked": string
"request_line.upon_approval": string
"request_line.upon_reject": string
"request_line.urgency": string
"request_line.user_input": string
"request_line.watch_list": string
"request_line.work_end": string
"request_line.work_notes": string
"request_line.work_notes_list": string
"request_line.work_start": string
"reserved_for.accumulated_roles": string
"reserved_for.active": string
"reserved_for.avatar": string
"reserved_for.building": string
"reserved_for.calendar_integration": string
"reserved_for.city": string
"reserved_for.company": string
"reserved_for.cost_center": string
"reserved_for.country": string
"reserved_for.date_format": string
"reserved_for.default_perspective": string
"reserved_for.department": string
"reserved_for.email": string
"reserved_for.employee_number": string
"reserved_for.enable_multifactor_authn": string
"reserved_for.failed_attempts": string
"reserved_for.first_name": string
"reserved_for.gender": string
"reserved_for.home_phone": string
"reserved_for.internal_integration_user": string
"reserved_for.introduction": string
"reserved_for.last_login": string
"reserved_for.last_login_time": string
"reserved_for.last_name": string
"reserved_for.ldap_server": string
"reserved_for.location": string
"reserved_for.locked_out": string
"reserved_for.manager": string
"reserved_for.middle_name": string
"reserved_for.mobile_phone": string
"reserved_for.name": string
"reserved_for.notification": string
"reserved_for.password_needs_reset": string
"reserved_for.phone": string
"reserved_for.photo": string
"reserved_for.preferred_language": string
"reserved_for.roles": string
"reserved_for.schedule": string
"reserved_for.source": string
"reserved_for.state": string
"reserved_for.street": string
"reserved_for.sys_class_name": string
"reserved_for.sys_created_by": string
"reserved_for.sys_created_on": string
"reserved_for.sys_domain": string
"reserved_for.sys_domain_path": string
"reserved_for.sys_id": string
"reserved_for.sys_mod_count": string
"reserved_for.sys_updated_by": string
"reserved_for.sys_updated_on": string
"reserved_for.time_format": string
"reserved_for.time_zone": string
"reserved_for.title": string
"reserved_for.user_name": string
"reserved_for.user_password": string
"reserved_for.vip": string
"reserved_for.web_service_access_only": string
"reserved_for.zip": string
"stockroom.assignment_group": string
"stockroom.external": string
"stockroom.location": string
"stockroom.manager": string
"stockroom.name": string
"stockroom.sys_created_by": string
"stockroom.sys_created_on": string
"stockroom.sys_domain": string
"stockroom.sys_domain_path": string
"stockroom.sys_id": string
"stockroom.sys_mod_count": string
"stockroom.sys_updated_by": string
"stockroom.sys_updated_on": string
"stockroom.type": string
"supported_by.accumulated_roles": string
"supported_by.active": string
"supported_by.avatar": string
"supported_by.building": string
"supported_by.calendar_integration": string
"supported_by.city": string
"supported_by.company": string
"supported_by.cost_center": string
"supported_by.country": string
"supported_by.date_format": string
"supported_by.default_perspective": string
"supported_by.department": string
"supported_by.email": string
"supported_by.employee_number": string
"supported_by.enable_multifactor_authn": string
"supported_by.failed_attempts": string
"supported_by.first_name": string
"supported_by.gender": string
"supported_by.home_phone": string
"supported_by.internal_integration_user": string
"supported_by.introduction": string
"supported_by.last_login": string
"supported_by.last_login_time": string
"supported_by.last_name": string
"supported_by.ldap_server": string
"supported_by.location": string
"supported_by.locked_out": string
"supported_by.manager": string
"supported_by.middle_name": string
"supported_by.mobile_phone": string
"supported_by.name": string
"supported_by.notification": string
"supported_by.password_needs_reset": string
"supported_by.phone": string
"supported_by.photo": string
"supported_by.preferred_language": string
"supported_by.roles": string
"supported_by.schedule": string
"supported_by.source": string
"supported_by.state": string
"supported_by.street": string
"supported_by.sys_class_name": string
"supported_by.sys_created_by": string
"supported_by.sys_created_on": string
"supported_by.sys_domain": string
"supported_by.sys_domain_path": string
"supported_by.sys_id": string
"supported_by.sys_mod_count": string
"supported_by.sys_updated_by": string
"supported_by.sys_updated_on": string
"supported_by.time_format": string
"supported_by.time_zone": string
"supported_by.title": string
"supported_by.user_name": string
"supported_by.user_password": string
"supported_by.vip": string
"supported_by.web_service_access_only": string
"supported_by.zip": string
"support_group.active": string
"support_group.cost_center": string
"support_group.default_assignee": string
"support_group.description": string
"support_group.email": string
"support_group.exclude_manager": string
"support_group.include_members": string
"support_group.manager": string
"support_group.name": string
"support_group.parent": string
"support_group.roles": string
"support_group.source": string
"support_group.sys_created_by": string
"support_group.sys_created_on": string
"support_group.sys_id": string
"support_group.sys_mod_count": string
"support_group.sys_updated_by": string
"support_group.sys_updated_on": string
"support_group.type": string
"vendor.apple_icon": string
"vendor.banner_image": string
"vendor.banner_image_light": string
"vendor.banner_text": string
"vendor.city": string
"vendor.contact": string
"vendor.country": string
"vendor.customer": string
"vendor.discount": string
"vendor.fax_phone": string
"vendor.fiscal_year": string
"vendor.latitude": string
"vendor.lat_long_error": string
"vendor.longitude": string
"vendor.manufacturer": string
"vendor.market_cap": string
"vendor.name": string
"vendor.notes": string
"vendor.num_employees": string
"vendor.parent": string
"vendor.phone": string
"vendor.primary": string
"vendor.profits": string
"vendor.publicly_traded": string
"vendor.rank_tier": string
"vendor.revenue_per_year": string
"vendor.state": string
"vendor.stock_price": string
"vendor.stock_symbol": string
"vendor.street": string
"vendor.sys_class_name": string
"vendor.sys_created_by": string
"vendor.sys_created_on": string
"vendor.sys_id": string
"vendor.sys_mod_count": string
"vendor.sys_updated_by": string
"vendor.sys_updated_on": string
"vendor.theme": string
"vendor.vendor": string
"vendor.vendor_manager": string
"vendor.vendor_type": string
"vendor.website": string
"vendor.zip": string;
      }
    }
   