declare interface cmn_department {
      business_unit: GlideElement<cmn_department, glideElementType.g_reference<business_unit>>;
company: GlideElement<cmn_department, glideElementType.g_reference<core_company>>;
cost_center: GlideElement<cmn_department, glideElementType.g_reference<cmn_cost_center>>;
dept_head: GlideElement<cmn_department, glideElementType.g_reference<sys_user>>;
description: GlideElement<cmn_department, glideElementType.defaultType>;
head_count: GlideElement<cmn_department, glideElementType.defaultType>;
id: GlideElement<cmn_department, glideElementType.defaultType>;
name: GlideElement<cmn_department, glideElementType.defaultType>;
parent: GlideElement<cmn_department, glideElementType.g_reference<cmn_department>>;
primary_contact: GlideElement<cmn_department, glideElementType.g_reference<sys_user>>;
sys_created_by: GlideElement<cmn_department, glideElementType.defaultType>;
sys_created_on: GlideElement<cmn_department, glideElementType.g_glide_date_time>;
sys_id: GlideElement<cmn_department, glideElementType.defaultType>;
sys_mod_count: GlideElement<cmn_department, glideElementType.defaultType>;
sys_updated_by: GlideElement<cmn_department, glideElementType.defaultType>;
sys_updated_on: GlideElement<cmn_department, glideElementType.g_glide_date_time>;
      _referenceKeys: never | {
        "business_unit.bu_head": string
"business_unit.company": string
"business_unit.description": string
"business_unit.hierarchy_level": string
"business_unit.name": string
"business_unit.parent": string
"business_unit.sys_created_by": string
"business_unit.sys_created_on": string
"business_unit.sys_domain": string
"business_unit.sys_domain_path": string
"business_unit.sys_id": string
"business_unit.sys_mod_count": string
"business_unit.sys_updated_by": string
"business_unit.sys_updated_on": string
"company.apple_icon": string
"company.banner_image": string
"company.banner_image_light": string
"company.banner_text": string
"company.city": string
"company.contact": string
"company.country": string
"company.customer": string
"company.discount": string
"company.fax_phone": string
"company.fiscal_year": string
"company.latitude": string
"company.lat_long_error": string
"company.longitude": string
"company.manufacturer": string
"company.market_cap": string
"company.name": string
"company.notes": string
"company.num_employees": string
"company.parent": string
"company.phone": string
"company.primary": string
"company.profits": string
"company.publicly_traded": string
"company.rank_tier": string
"company.revenue_per_year": string
"company.state": string
"company.stock_price": string
"company.stock_symbol": string
"company.street": string
"company.sys_class_name": string
"company.sys_created_by": string
"company.sys_created_on": string
"company.sys_id": string
"company.sys_mod_count": string
"company.sys_updated_by": string
"company.sys_updated_on": string
"company.theme": string
"company.vendor": string
"company.vendor_manager": string
"company.vendor_type": string
"company.website": string
"company.zip": string
"cost_center.account_number": string
"cost_center.code": string
"cost_center.location": string
"cost_center.manager": string
"cost_center.name": string
"cost_center.parent": string
"cost_center.sys_created_by": string
"cost_center.sys_created_on": string
"cost_center.sys_id": string
"cost_center.sys_mod_count": string
"cost_center.sys_updated_by": string
"cost_center.sys_updated_on": string
"cost_center.valid_from": string
"cost_center.valid_to": string
"dept_head.accumulated_roles": string
"dept_head.active": string
"dept_head.avatar": string
"dept_head.building": string
"dept_head.calendar_integration": string
"dept_head.city": string
"dept_head.company": string
"dept_head.cost_center": string
"dept_head.country": string
"dept_head.date_format": string
"dept_head.default_perspective": string
"dept_head.department": string
"dept_head.email": string
"dept_head.employee_number": string
"dept_head.enable_multifactor_authn": string
"dept_head.failed_attempts": string
"dept_head.first_name": string
"dept_head.gender": string
"dept_head.home_phone": string
"dept_head.internal_integration_user": string
"dept_head.introduction": string
"dept_head.last_login": string
"dept_head.last_login_time": string
"dept_head.last_name": string
"dept_head.ldap_server": string
"dept_head.location": string
"dept_head.locked_out": string
"dept_head.manager": string
"dept_head.middle_name": string
"dept_head.mobile_phone": string
"dept_head.name": string
"dept_head.notification": string
"dept_head.password_needs_reset": string
"dept_head.phone": string
"dept_head.photo": string
"dept_head.preferred_language": string
"dept_head.roles": string
"dept_head.schedule": string
"dept_head.source": string
"dept_head.state": string
"dept_head.street": string
"dept_head.sys_class_name": string
"dept_head.sys_created_by": string
"dept_head.sys_created_on": string
"dept_head.sys_domain": string
"dept_head.sys_domain_path": string
"dept_head.sys_id": string
"dept_head.sys_mod_count": string
"dept_head.sys_updated_by": string
"dept_head.sys_updated_on": string
"dept_head.time_format": string
"dept_head.time_zone": string
"dept_head.title": string
"dept_head.user_name": string
"dept_head.user_password": string
"dept_head.vip": string
"dept_head.web_service_access_only": string
"dept_head.zip": string
"parent.business_unit": string
"parent.company": string
"parent.cost_center": string
"parent.dept_head": string
"parent.description": string
"parent.head_count": string
"parent.id": string
"parent.name": string
"parent.parent": string
"parent.primary_contact": string
"parent.sys_created_by": string
"parent.sys_created_on": string
"parent.sys_id": string
"parent.sys_mod_count": string
"parent.sys_updated_by": string
"parent.sys_updated_on": string
"primary_contact.accumulated_roles": string
"primary_contact.active": string
"primary_contact.avatar": string
"primary_contact.building": string
"primary_contact.calendar_integration": string
"primary_contact.city": string
"primary_contact.company": string
"primary_contact.cost_center": string
"primary_contact.country": string
"primary_contact.date_format": string
"primary_contact.default_perspective": string
"primary_contact.department": string
"primary_contact.email": string
"primary_contact.employee_number": string
"primary_contact.enable_multifactor_authn": string
"primary_contact.failed_attempts": string
"primary_contact.first_name": string
"primary_contact.gender": string
"primary_contact.home_phone": string
"primary_contact.internal_integration_user": string
"primary_contact.introduction": string
"primary_contact.last_login": string
"primary_contact.last_login_time": string
"primary_contact.last_name": string
"primary_contact.ldap_server": string
"primary_contact.location": string
"primary_contact.locked_out": string
"primary_contact.manager": string
"primary_contact.middle_name": string
"primary_contact.mobile_phone": string
"primary_contact.name": string
"primary_contact.notification": string
"primary_contact.password_needs_reset": string
"primary_contact.phone": string
"primary_contact.photo": string
"primary_contact.preferred_language": string
"primary_contact.roles": string
"primary_contact.schedule": string
"primary_contact.source": string
"primary_contact.state": string
"primary_contact.street": string
"primary_contact.sys_class_name": string
"primary_contact.sys_created_by": string
"primary_contact.sys_created_on": string
"primary_contact.sys_domain": string
"primary_contact.sys_domain_path": string
"primary_contact.sys_id": string
"primary_contact.sys_mod_count": string
"primary_contact.sys_updated_by": string
"primary_contact.sys_updated_on": string
"primary_contact.time_format": string
"primary_contact.time_zone": string
"primary_contact.title": string
"primary_contact.user_name": string
"primary_contact.user_password": string
"primary_contact.vip": string
"primary_contact.web_service_access_only": string
"primary_contact.zip": string;
      }
    }
   