declare interface pa_chart_color_schemes {
      color_1: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_10: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_11: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_12: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_13: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_14: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_15: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_16: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_17: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_18: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_19: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_2: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_20: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_21: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_22: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_23: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_24: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_25: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_26: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_27: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_28: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_29: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_3: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_30: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_31: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_32: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_4: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_5: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_6: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_7: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_8: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
color_9: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_report_color>>;
description: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
name: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_domain: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_domain_path: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_id: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_overrides: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<pa_chart_color_schemes>>;
sys_class_name: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_created_by: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_created_on: GlideElement<pa_chart_color_schemes, glideElementType.g_glide_date_time>;
sys_mod_count: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_name: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_package: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_package>>;
sys_policy: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_scope: GlideElement<pa_chart_color_schemes, glideElementType.g_reference<sys_scope>>;
sys_updated_by: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
sys_updated_on: GlideElement<pa_chart_color_schemes, glideElementType.g_glide_date_time>;
sys_update_name: GlideElement<pa_chart_color_schemes, glideElementType.defaultType>;
      _referenceKeys: never | {
        "color_1.color": string
"color_1.display": string
"color_1.name": string
"color_1.sys_id": string
"color_1.sys_class_name": string
"color_1.sys_created_by": string
"color_1.sys_created_on": string
"color_1.sys_mod_count": string
"color_1.sys_name": string
"color_1.sys_package": string
"color_1.sys_policy": string
"color_1.sys_scope": string
"color_1.sys_updated_by": string
"color_1.sys_updated_on": string
"color_1.sys_update_name": string
"color_10.color": string
"color_10.display": string
"color_10.name": string
"color_10.sys_id": string
"color_10.sys_class_name": string
"color_10.sys_created_by": string
"color_10.sys_created_on": string
"color_10.sys_mod_count": string
"color_10.sys_name": string
"color_10.sys_package": string
"color_10.sys_policy": string
"color_10.sys_scope": string
"color_10.sys_updated_by": string
"color_10.sys_updated_on": string
"color_10.sys_update_name": string
"color_11.color": string
"color_11.display": string
"color_11.name": string
"color_11.sys_id": string
"color_11.sys_class_name": string
"color_11.sys_created_by": string
"color_11.sys_created_on": string
"color_11.sys_mod_count": string
"color_11.sys_name": string
"color_11.sys_package": string
"color_11.sys_policy": string
"color_11.sys_scope": string
"color_11.sys_updated_by": string
"color_11.sys_updated_on": string
"color_11.sys_update_name": string
"color_12.color": string
"color_12.display": string
"color_12.name": string
"color_12.sys_id": string
"color_12.sys_class_name": string
"color_12.sys_created_by": string
"color_12.sys_created_on": string
"color_12.sys_mod_count": string
"color_12.sys_name": string
"color_12.sys_package": string
"color_12.sys_policy": string
"color_12.sys_scope": string
"color_12.sys_updated_by": string
"color_12.sys_updated_on": string
"color_12.sys_update_name": string
"color_13.color": string
"color_13.display": string
"color_13.name": string
"color_13.sys_id": string
"color_13.sys_class_name": string
"color_13.sys_created_by": string
"color_13.sys_created_on": string
"color_13.sys_mod_count": string
"color_13.sys_name": string
"color_13.sys_package": string
"color_13.sys_policy": string
"color_13.sys_scope": string
"color_13.sys_updated_by": string
"color_13.sys_updated_on": string
"color_13.sys_update_name": string
"color_14.color": string
"color_14.display": string
"color_14.name": string
"color_14.sys_id": string
"color_14.sys_class_name": string
"color_14.sys_created_by": string
"color_14.sys_created_on": string
"color_14.sys_mod_count": string
"color_14.sys_name": string
"color_14.sys_package": string
"color_14.sys_policy": string
"color_14.sys_scope": string
"color_14.sys_updated_by": string
"color_14.sys_updated_on": string
"color_14.sys_update_name": string
"color_15.color": string
"color_15.display": string
"color_15.name": string
"color_15.sys_id": string
"color_15.sys_class_name": string
"color_15.sys_created_by": string
"color_15.sys_created_on": string
"color_15.sys_mod_count": string
"color_15.sys_name": string
"color_15.sys_package": string
"color_15.sys_policy": string
"color_15.sys_scope": string
"color_15.sys_updated_by": string
"color_15.sys_updated_on": string
"color_15.sys_update_name": string
"color_16.color": string
"color_16.display": string
"color_16.name": string
"color_16.sys_id": string
"color_16.sys_class_name": string
"color_16.sys_created_by": string
"color_16.sys_created_on": string
"color_16.sys_mod_count": string
"color_16.sys_name": string
"color_16.sys_package": string
"color_16.sys_policy": string
"color_16.sys_scope": string
"color_16.sys_updated_by": string
"color_16.sys_updated_on": string
"color_16.sys_update_name": string
"color_17.color": string
"color_17.display": string
"color_17.name": string
"color_17.sys_id": string
"color_17.sys_class_name": string
"color_17.sys_created_by": string
"color_17.sys_created_on": string
"color_17.sys_mod_count": string
"color_17.sys_name": string
"color_17.sys_package": string
"color_17.sys_policy": string
"color_17.sys_scope": string
"color_17.sys_updated_by": string
"color_17.sys_updated_on": string
"color_17.sys_update_name": string
"color_18.color": string
"color_18.display": string
"color_18.name": string
"color_18.sys_id": string
"color_18.sys_class_name": string
"color_18.sys_created_by": string
"color_18.sys_created_on": string
"color_18.sys_mod_count": string
"color_18.sys_name": string
"color_18.sys_package": string
"color_18.sys_policy": string
"color_18.sys_scope": string
"color_18.sys_updated_by": string
"color_18.sys_updated_on": string
"color_18.sys_update_name": string
"color_19.color": string
"color_19.display": string
"color_19.name": string
"color_19.sys_id": string
"color_19.sys_class_name": string
"color_19.sys_created_by": string
"color_19.sys_created_on": string
"color_19.sys_mod_count": string
"color_19.sys_name": string
"color_19.sys_package": string
"color_19.sys_policy": string
"color_19.sys_scope": string
"color_19.sys_updated_by": string
"color_19.sys_updated_on": string
"color_19.sys_update_name": string
"color_2.color": string
"color_2.display": string
"color_2.name": string
"color_2.sys_id": string
"color_2.sys_class_name": string
"color_2.sys_created_by": string
"color_2.sys_created_on": string
"color_2.sys_mod_count": string
"color_2.sys_name": string
"color_2.sys_package": string
"color_2.sys_policy": string
"color_2.sys_scope": string
"color_2.sys_updated_by": string
"color_2.sys_updated_on": string
"color_2.sys_update_name": string
"color_20.color": string
"color_20.display": string
"color_20.name": string
"color_20.sys_id": string
"color_20.sys_class_name": string
"color_20.sys_created_by": string
"color_20.sys_created_on": string
"color_20.sys_mod_count": string
"color_20.sys_name": string
"color_20.sys_package": string
"color_20.sys_policy": string
"color_20.sys_scope": string
"color_20.sys_updated_by": string
"color_20.sys_updated_on": string
"color_20.sys_update_name": string
"color_21.color": string
"color_21.display": string
"color_21.name": string
"color_21.sys_id": string
"color_21.sys_class_name": string
"color_21.sys_created_by": string
"color_21.sys_created_on": string
"color_21.sys_mod_count": string
"color_21.sys_name": string
"color_21.sys_package": string
"color_21.sys_policy": string
"color_21.sys_scope": string
"color_21.sys_updated_by": string
"color_21.sys_updated_on": string
"color_21.sys_update_name": string
"color_22.color": string
"color_22.display": string
"color_22.name": string
"color_22.sys_id": string
"color_22.sys_class_name": string
"color_22.sys_created_by": string
"color_22.sys_created_on": string
"color_22.sys_mod_count": string
"color_22.sys_name": string
"color_22.sys_package": string
"color_22.sys_policy": string
"color_22.sys_scope": string
"color_22.sys_updated_by": string
"color_22.sys_updated_on": string
"color_22.sys_update_name": string
"color_23.color": string
"color_23.display": string
"color_23.name": string
"color_23.sys_id": string
"color_23.sys_class_name": string
"color_23.sys_created_by": string
"color_23.sys_created_on": string
"color_23.sys_mod_count": string
"color_23.sys_name": string
"color_23.sys_package": string
"color_23.sys_policy": string
"color_23.sys_scope": string
"color_23.sys_updated_by": string
"color_23.sys_updated_on": string
"color_23.sys_update_name": string
"color_24.color": string
"color_24.display": string
"color_24.name": string
"color_24.sys_id": string
"color_24.sys_class_name": string
"color_24.sys_created_by": string
"color_24.sys_created_on": string
"color_24.sys_mod_count": string
"color_24.sys_name": string
"color_24.sys_package": string
"color_24.sys_policy": string
"color_24.sys_scope": string
"color_24.sys_updated_by": string
"color_24.sys_updated_on": string
"color_24.sys_update_name": string
"color_25.color": string
"color_25.display": string
"color_25.name": string
"color_25.sys_id": string
"color_25.sys_class_name": string
"color_25.sys_created_by": string
"color_25.sys_created_on": string
"color_25.sys_mod_count": string
"color_25.sys_name": string
"color_25.sys_package": string
"color_25.sys_policy": string
"color_25.sys_scope": string
"color_25.sys_updated_by": string
"color_25.sys_updated_on": string
"color_25.sys_update_name": string
"color_26.color": string
"color_26.display": string
"color_26.name": string
"color_26.sys_id": string
"color_26.sys_class_name": string
"color_26.sys_created_by": string
"color_26.sys_created_on": string
"color_26.sys_mod_count": string
"color_26.sys_name": string
"color_26.sys_package": string
"color_26.sys_policy": string
"color_26.sys_scope": string
"color_26.sys_updated_by": string
"color_26.sys_updated_on": string
"color_26.sys_update_name": string
"color_27.color": string
"color_27.display": string
"color_27.name": string
"color_27.sys_id": string
"color_27.sys_class_name": string
"color_27.sys_created_by": string
"color_27.sys_created_on": string
"color_27.sys_mod_count": string
"color_27.sys_name": string
"color_27.sys_package": string
"color_27.sys_policy": string
"color_27.sys_scope": string
"color_27.sys_updated_by": string
"color_27.sys_updated_on": string
"color_27.sys_update_name": string
"color_28.color": string
"color_28.display": string
"color_28.name": string
"color_28.sys_id": string
"color_28.sys_class_name": string
"color_28.sys_created_by": string
"color_28.sys_created_on": string
"color_28.sys_mod_count": string
"color_28.sys_name": string
"color_28.sys_package": string
"color_28.sys_policy": string
"color_28.sys_scope": string
"color_28.sys_updated_by": string
"color_28.sys_updated_on": string
"color_28.sys_update_name": string
"color_29.color": string
"color_29.display": string
"color_29.name": string
"color_29.sys_id": string
"color_29.sys_class_name": string
"color_29.sys_created_by": string
"color_29.sys_created_on": string
"color_29.sys_mod_count": string
"color_29.sys_name": string
"color_29.sys_package": string
"color_29.sys_policy": string
"color_29.sys_scope": string
"color_29.sys_updated_by": string
"color_29.sys_updated_on": string
"color_29.sys_update_name": string
"color_3.color": string
"color_3.display": string
"color_3.name": string
"color_3.sys_id": string
"color_3.sys_class_name": string
"color_3.sys_created_by": string
"color_3.sys_created_on": string
"color_3.sys_mod_count": string
"color_3.sys_name": string
"color_3.sys_package": string
"color_3.sys_policy": string
"color_3.sys_scope": string
"color_3.sys_updated_by": string
"color_3.sys_updated_on": string
"color_3.sys_update_name": string
"color_30.color": string
"color_30.display": string
"color_30.name": string
"color_30.sys_id": string
"color_30.sys_class_name": string
"color_30.sys_created_by": string
"color_30.sys_created_on": string
"color_30.sys_mod_count": string
"color_30.sys_name": string
"color_30.sys_package": string
"color_30.sys_policy": string
"color_30.sys_scope": string
"color_30.sys_updated_by": string
"color_30.sys_updated_on": string
"color_30.sys_update_name": string
"color_31.color": string
"color_31.display": string
"color_31.name": string
"color_31.sys_id": string
"color_31.sys_class_name": string
"color_31.sys_created_by": string
"color_31.sys_created_on": string
"color_31.sys_mod_count": string
"color_31.sys_name": string
"color_31.sys_package": string
"color_31.sys_policy": string
"color_31.sys_scope": string
"color_31.sys_updated_by": string
"color_31.sys_updated_on": string
"color_31.sys_update_name": string
"color_32.color": string
"color_32.display": string
"color_32.name": string
"color_32.sys_id": string
"color_32.sys_class_name": string
"color_32.sys_created_by": string
"color_32.sys_created_on": string
"color_32.sys_mod_count": string
"color_32.sys_name": string
"color_32.sys_package": string
"color_32.sys_policy": string
"color_32.sys_scope": string
"color_32.sys_updated_by": string
"color_32.sys_updated_on": string
"color_32.sys_update_name": string
"color_4.color": string
"color_4.display": string
"color_4.name": string
"color_4.sys_id": string
"color_4.sys_class_name": string
"color_4.sys_created_by": string
"color_4.sys_created_on": string
"color_4.sys_mod_count": string
"color_4.sys_name": string
"color_4.sys_package": string
"color_4.sys_policy": string
"color_4.sys_scope": string
"color_4.sys_updated_by": string
"color_4.sys_updated_on": string
"color_4.sys_update_name": string
"color_5.color": string
"color_5.display": string
"color_5.name": string
"color_5.sys_id": string
"color_5.sys_class_name": string
"color_5.sys_created_by": string
"color_5.sys_created_on": string
"color_5.sys_mod_count": string
"color_5.sys_name": string
"color_5.sys_package": string
"color_5.sys_policy": string
"color_5.sys_scope": string
"color_5.sys_updated_by": string
"color_5.sys_updated_on": string
"color_5.sys_update_name": string
"color_6.color": string
"color_6.display": string
"color_6.name": string
"color_6.sys_id": string
"color_6.sys_class_name": string
"color_6.sys_created_by": string
"color_6.sys_created_on": string
"color_6.sys_mod_count": string
"color_6.sys_name": string
"color_6.sys_package": string
"color_6.sys_policy": string
"color_6.sys_scope": string
"color_6.sys_updated_by": string
"color_6.sys_updated_on": string
"color_6.sys_update_name": string
"color_7.color": string
"color_7.display": string
"color_7.name": string
"color_7.sys_id": string
"color_7.sys_class_name": string
"color_7.sys_created_by": string
"color_7.sys_created_on": string
"color_7.sys_mod_count": string
"color_7.sys_name": string
"color_7.sys_package": string
"color_7.sys_policy": string
"color_7.sys_scope": string
"color_7.sys_updated_by": string
"color_7.sys_updated_on": string
"color_7.sys_update_name": string
"color_8.color": string
"color_8.display": string
"color_8.name": string
"color_8.sys_id": string
"color_8.sys_class_name": string
"color_8.sys_created_by": string
"color_8.sys_created_on": string
"color_8.sys_mod_count": string
"color_8.sys_name": string
"color_8.sys_package": string
"color_8.sys_policy": string
"color_8.sys_scope": string
"color_8.sys_updated_by": string
"color_8.sys_updated_on": string
"color_8.sys_update_name": string
"color_9.color": string
"color_9.display": string
"color_9.name": string
"color_9.sys_id": string
"color_9.sys_class_name": string
"color_9.sys_created_by": string
"color_9.sys_created_on": string
"color_9.sys_mod_count": string
"color_9.sys_name": string
"color_9.sys_package": string
"color_9.sys_policy": string
"color_9.sys_scope": string
"color_9.sys_updated_by": string
"color_9.sys_updated_on": string
"color_9.sys_update_name": string
"sys_overrides.color_1": string
"sys_overrides.color_10": string
"sys_overrides.color_11": string
"sys_overrides.color_12": string
"sys_overrides.color_13": string
"sys_overrides.color_14": string
"sys_overrides.color_15": string
"sys_overrides.color_16": string
"sys_overrides.color_17": string
"sys_overrides.color_18": string
"sys_overrides.color_19": string
"sys_overrides.color_2": string
"sys_overrides.color_20": string
"sys_overrides.color_21": string
"sys_overrides.color_22": string
"sys_overrides.color_23": string
"sys_overrides.color_24": string
"sys_overrides.color_25": string
"sys_overrides.color_26": string
"sys_overrides.color_27": string
"sys_overrides.color_28": string
"sys_overrides.color_29": string
"sys_overrides.color_3": string
"sys_overrides.color_30": string
"sys_overrides.color_31": string
"sys_overrides.color_32": string
"sys_overrides.color_4": string
"sys_overrides.color_5": string
"sys_overrides.color_6": string
"sys_overrides.color_7": string
"sys_overrides.color_8": string
"sys_overrides.color_9": string
"sys_overrides.description": string
"sys_overrides.name": string
"sys_overrides.sys_domain": string
"sys_overrides.sys_domain_path": string
"sys_overrides.sys_id": string
"sys_overrides.sys_overrides": string
"sys_overrides.sys_class_name": string
"sys_overrides.sys_created_by": string
"sys_overrides.sys_created_on": string
"sys_overrides.sys_mod_count": string
"sys_overrides.sys_name": string
"sys_overrides.sys_package": string
"sys_overrides.sys_policy": string
"sys_overrides.sys_scope": string
"sys_overrides.sys_updated_by": string
"sys_overrides.sys_updated_on": string
"sys_overrides.sys_update_name": string
"sys_package.active": string
"sys_package.enforce_license": string
"sys_package.licensable": string
"sys_package.license_category": string
"sys_package.license_model": string
"sys_package.name": string
"sys_package.source": string
"sys_package.sys_class_name": string
"sys_package.sys_created_by": string
"sys_package.sys_created_on": string
"sys_package.sys_id": string
"sys_package.sys_mod_count": string
"sys_package.sys_updated_by": string
"sys_package.sys_updated_on": string
"sys_package.trackable": string
"sys_package.version": string
"sys_scope.can_edit_in_studio": string
"sys_scope.guided_setup_guid": string
"sys_scope.js_level": string
"sys_scope.logo": string
"sys_scope.private": string
"sys_scope.restrict_table_access": string
"sys_scope.runtime_access_tracking": string
"sys_scope.scope": string
"sys_scope.scoped_administration": string
"sys_scope.short_description": string
"sys_scope.sys_id": string
"sys_scope.template": string
"sys_scope.vendor": string
"sys_scope.vendor_prefix": string
"sys_scope.active": string
"sys_scope.enforce_license": string
"sys_scope.licensable": string
"sys_scope.license_category": string
"sys_scope.license_model": string
"sys_scope.name": string
"sys_scope.source": string
"sys_scope.sys_class_name": string
"sys_scope.sys_created_by": string
"sys_scope.sys_created_on": string
"sys_scope.sys_mod_count": string
"sys_scope.sys_updated_by": string
"sys_scope.sys_updated_on": string
"sys_scope.trackable": string
"sys_scope.version": string;
      }
    }
   