declare interface sc_req_item {
      backordered: GlideElement<sc_req_item, glideElementType.g_boolean>;
billable: GlideElement<sc_req_item, glideElementType.g_boolean>;
cat_item: GlideElement<sc_req_item, glideElementType.g_reference<sc_cat_item>>;
configuration_item: GlideElement<sc_req_item, glideElementType.g_reference<cmdb_ci>>;
context: GlideElement<sc_req_item, glideElementType.g_reference<wf_context>>;
estimated_delivery: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
order_guide: GlideElement<sc_req_item, glideElementType.g_reference<sc_cat_item_guide>>;
price: GlideElement<sc_req_item, glideElementType.g_currency>;
quantity: GlideElement<sc_req_item, glideElementType.defaultType>;
recurring_frequency: GlideElement<sc_req_item, glideElementType.g_choice<string>>;
recurring_price: GlideElement<sc_req_item, glideElementType.g_price>;
request: GlideElement<sc_req_item, glideElementType.g_reference<sc_request>>;
sc_catalog: GlideElement<sc_req_item, glideElementType.g_reference<sc_catalog>>;
stage: GlideElement<sc_req_item, glideElementType.defaultType>;
sys_id: GlideElement<sc_req_item, glideElementType.defaultType>;
active: GlideElement<sc_req_item, glideElementType.g_boolean>;
activity_due: GlideElement<sc_req_item, glideElementType.defaultType>;
additional_assignee_list: GlideElement<sc_req_item, glideElementType.defaultType>;
approval: GlideElement<sc_req_item, glideElementType.defaultType>;
approval_history: GlideElement<sc_req_item, glideElementType.defaultType>;
approval_set: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
assigned_to: GlideElement<sc_req_item, glideElementType.g_reference<sys_user>>;
assignment_group: GlideElement<sc_req_item, glideElementType.g_reference<sys_user_group>>;
business_duration: GlideElement<sc_req_item, glideElementType.defaultType>;
business_service: GlideElement<sc_req_item, glideElementType.g_reference<cmdb_ci_service>>;
calendar_duration: GlideElement<sc_req_item, glideElementType.defaultType>;
closed_at: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
closed_by: GlideElement<sc_req_item, glideElementType.g_reference<sys_user>>;
close_notes: GlideElement<sc_req_item, glideElementType.defaultType>;
cmdb_ci: GlideElement<sc_req_item, glideElementType.g_reference<cmdb_ci>>;
comments: GlideElement<sc_req_item, glideElementType.defaultType>;
comments_and_work_notes: GlideElement<sc_req_item, glideElementType.defaultType>;
company: GlideElement<sc_req_item, glideElementType.g_reference<core_company>>;
contact_type: GlideElement<sc_req_item, glideElementType.defaultType>;
contract: GlideElement<sc_req_item, glideElementType.g_reference<ast_contract>>;
correlation_display: GlideElement<sc_req_item, glideElementType.defaultType>;
correlation_id: GlideElement<sc_req_item, glideElementType.defaultType>;
delivery_plan: GlideElement<sc_req_item, glideElementType.g_reference<sc_cat_item_delivery_plan>>;
delivery_task: GlideElement<sc_req_item, glideElementType.g_reference<sc_cat_item_delivery_task>>;
description: GlideElement<sc_req_item, glideElementType.defaultType>;
due_date: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
escalation: GlideElement<sc_req_item, glideElementType.defaultType>;
expected_start: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
follow_up: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
group_list: GlideElement<sc_req_item, glideElementType.defaultType>;
impact: GlideElement<sc_req_item, glideElementType.defaultType>;
knowledge: GlideElement<sc_req_item, glideElementType.g_boolean>;
location: GlideElement<sc_req_item, glideElementType.g_reference<cmn_location>>;
made_sla: GlideElement<sc_req_item, glideElementType.g_boolean>;
number: GlideElement<sc_req_item, glideElementType.defaultType>;
opened_at: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
opened_by: GlideElement<sc_req_item, glideElementType.g_reference<sys_user>>;
order: GlideElement<sc_req_item, glideElementType.defaultType>;
parent: GlideElement<sc_req_item, glideElementType.g_reference<task>>;
priority: GlideElement<sc_req_item, glideElementType.defaultType>;
reassignment_count: GlideElement<sc_req_item, glideElementType.defaultType>;
service_offering: GlideElement<sc_req_item, glideElementType.g_reference<service_offering>>;
short_description: GlideElement<sc_req_item, glideElementType.defaultType>;
sla_due: GlideElement<sc_req_item, glideElementType.defaultType>;
state: GlideElement<sc_req_item, glideElementType.defaultType>;
sys_class_name: GlideElement<sc_req_item, glideElementType.defaultType>;
sys_created_by: GlideElement<sc_req_item, glideElementType.defaultType>;
sys_created_on: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
sys_domain: GlideElement<sc_req_item, glideElementType.defaultType>;
sys_domain_path: GlideElement<sc_req_item, glideElementType.defaultType>;
sys_mod_count: GlideElement<sc_req_item, glideElementType.defaultType>;
sys_updated_by: GlideElement<sc_req_item, glideElementType.defaultType>;
sys_updated_on: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
time_worked: GlideElement<sc_req_item, glideElementType.defaultType>;
upon_approval: GlideElement<sc_req_item, glideElementType.defaultType>;
upon_reject: GlideElement<sc_req_item, glideElementType.defaultType>;
urgency: GlideElement<sc_req_item, glideElementType.defaultType>;
user_input: GlideElement<sc_req_item, glideElementType.defaultType>;
watch_list: GlideElement<sc_req_item, glideElementType.defaultType>;
work_end: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
work_notes: GlideElement<sc_req_item, glideElementType.defaultType>;
work_notes_list: GlideElement<sc_req_item, glideElementType.defaultType>;
work_start: GlideElement<sc_req_item, glideElementType.g_glide_date_time>;
      _referenceKeys: never | {
        "cat_item.active": string
"cat_item.availability": string
"cat_item.billable": string
"cat_item.category": string
"cat_item.cost": string
"cat_item.custom_cart": string
"cat_item.delivery_plan": string
"cat_item.delivery_plan_script": string
"cat_item.delivery_time": string
"cat_item.description": string
"cat_item.display_price_property": string
"cat_item.entitlement_script": string
"cat_item.group": string
"cat_item.hide_sp": string
"cat_item.icon": string
"cat_item.ignore_price": string
"cat_item.image": string
"cat_item.list_price": string
"cat_item.location": string
"cat_item.mandatory_attachment": string
"cat_item.meta": string
"cat_item.mobile_hide_price": string
"cat_item.mobile_picture": string
"cat_item.mobile_picture_type": string
"cat_item.model": string
"cat_item.name": string
"cat_item.no_attachment_v2": string
"cat_item.no_cart": string
"cat_item.no_cart_v2": string
"cat_item.no_delivery_time_v2": string
"cat_item.no_order": string
"cat_item.no_order_now": string
"cat_item.no_proceed_checkout": string
"cat_item.no_quantity": string
"cat_item.no_quantity_v2": string
"cat_item.no_search": string
"cat_item.no_wishlist_v2": string
"cat_item.omit_price": string
"cat_item.order": string
"cat_item.ordered_item_link": string
"cat_item.picture": string
"cat_item.preview": string
"cat_item.price": string
"cat_item.recurring_frequency": string
"cat_item.recurring_price": string
"cat_item.request_method": string
"cat_item.roles": string
"cat_item.sc_catalogs": string
"cat_item.sc_ic_item_staging": string
"cat_item.sc_ic_version": string
"cat_item.short_description": string
"cat_item.show_variable_help_on_load": string
"cat_item.start_closed": string
"cat_item.sys_id": string
"cat_item.template": string
"cat_item.type": string
"cat_item.use_sc_layout": string
"cat_item.vendor": string
"cat_item.visible_bundle": string
"cat_item.visible_guide": string
"cat_item.visible_standalone": string
"cat_item.workflow": string
"cat_item.sys_class_name": string
"cat_item.sys_created_by": string
"cat_item.sys_created_on": string
"cat_item.sys_mod_count": string
"cat_item.sys_name": string
"cat_item.sys_package": string
"cat_item.sys_policy": string
"cat_item.sys_scope": string
"cat_item.sys_updated_by": string
"cat_item.sys_updated_on": string
"cat_item.sys_update_name": string
"configuration_item.asset": string
"configuration_item.asset_tag": string
"configuration_item.assigned": string
"configuration_item.assigned_to": string
"configuration_item.assignment_group": string
"configuration_item.attributes": string
"configuration_item.can_print": string
"configuration_item.category": string
"configuration_item.change_control": string
"configuration_item.checked_in": string
"configuration_item.checked_out": string
"configuration_item.comments": string
"configuration_item.company": string
"configuration_item.correlation_id": string
"configuration_item.cost": string
"configuration_item.cost_cc": string
"configuration_item.cost_center": string
"configuration_item.delivery_date": string
"configuration_item.department": string
"configuration_item.discovery_source": string
"configuration_item.dns_domain": string
"configuration_item.due": string
"configuration_item.due_in": string
"configuration_item.duplicate_of": string
"configuration_item.fault_count": string
"configuration_item.first_discovered": string
"configuration_item.fqdn": string
"configuration_item.gl_account": string
"configuration_item.install_date": string
"configuration_item.install_status": string
"configuration_item.invoice_number": string
"configuration_item.ip_address": string
"configuration_item.justification": string
"configuration_item.last_discovered": string
"configuration_item.lease_id": string
"configuration_item.location": string
"configuration_item.mac_address": string
"configuration_item.maintenance_schedule": string
"configuration_item.managed_by": string
"configuration_item.manufacturer": string
"configuration_item.model_id": string
"configuration_item.model_number": string
"configuration_item.monitor": string
"configuration_item.name": string
"configuration_item.operational_status": string
"configuration_item.order_date": string
"configuration_item.owned_by": string
"configuration_item.po_number": string
"configuration_item.purchase_date": string
"configuration_item.schedule": string
"configuration_item.serial_number": string
"configuration_item.short_description": string
"configuration_item.skip_sync": string
"configuration_item.start_date": string
"configuration_item.subcategory": string
"configuration_item.supported_by": string
"configuration_item.support_group": string
"configuration_item.sys_class_name": string
"configuration_item.sys_class_path": string
"configuration_item.sys_created_by": string
"configuration_item.sys_created_on": string
"configuration_item.sys_domain": string
"configuration_item.sys_domain_path": string
"configuration_item.sys_id": string
"configuration_item.sys_mod_count": string
"configuration_item.sys_updated_by": string
"configuration_item.sys_updated_on": string
"configuration_item.unverified": string
"configuration_item.vendor": string
"configuration_item.warranty_expiration": string
"context.active": string
"context.activity_count": string
"context.activity_index": string
"context.after_business_rules": string
"context.auto_start": string
"context.column_renderer": string
"context.cumulated_avg_ert": string
"context.due": string
"context.ended": string
"context.ert_long_running_actions": string
"context.ert_outlier_workflow_actions": string
"context.id": string
"context.name": string
"context.parent": string
"context.parent_activity": string
"context.requires_ert": string
"context.result": string
"context.return_value": string
"context.running_duration": string
"context.schedule": string
"context.scratchpad": string
"context.stage": string
"context.stage_state": string
"context.started": string
"context.started_by": string
"context.state": string
"context.sys_created_by": string
"context.sys_created_on": string
"context.sys_domain": string
"context.sys_domain_path": string
"context.sys_id": string
"context.sys_mod_count": string
"context.sys_updated_by": string
"context.sys_updated_on": string
"context.table": string
"context.timezone": string
"context.without_current_wf_actions": string
"context.workflow": string
"context.workflow_version": string
"order_guide.cascade": string
"order_guide.include_items": string
"order_guide.order_to_cart": string
"order_guide.script": string
"order_guide.sys_id": string
"order_guide.two_step": string
"order_guide.validator": string
"order_guide.active": string
"order_guide.availability": string
"order_guide.billable": string
"order_guide.category": string
"order_guide.cost": string
"order_guide.custom_cart": string
"order_guide.delivery_plan": string
"order_guide.delivery_plan_script": string
"order_guide.delivery_time": string
"order_guide.description": string
"order_guide.display_price_property": string
"order_guide.entitlement_script": string
"order_guide.group": string
"order_guide.hide_sp": string
"order_guide.icon": string
"order_guide.ignore_price": string
"order_guide.image": string
"order_guide.list_price": string
"order_guide.location": string
"order_guide.mandatory_attachment": string
"order_guide.meta": string
"order_guide.mobile_hide_price": string
"order_guide.mobile_picture": string
"order_guide.mobile_picture_type": string
"order_guide.model": string
"order_guide.name": string
"order_guide.no_attachment_v2": string
"order_guide.no_cart": string
"order_guide.no_cart_v2": string
"order_guide.no_delivery_time_v2": string
"order_guide.no_order": string
"order_guide.no_order_now": string
"order_guide.no_proceed_checkout": string
"order_guide.no_quantity": string
"order_guide.no_quantity_v2": string
"order_guide.no_search": string
"order_guide.no_wishlist_v2": string
"order_guide.omit_price": string
"order_guide.order": string
"order_guide.ordered_item_link": string
"order_guide.picture": string
"order_guide.preview": string
"order_guide.price": string
"order_guide.recurring_frequency": string
"order_guide.recurring_price": string
"order_guide.request_method": string
"order_guide.roles": string
"order_guide.sc_catalogs": string
"order_guide.sc_ic_item_staging": string
"order_guide.sc_ic_version": string
"order_guide.short_description": string
"order_guide.show_variable_help_on_load": string
"order_guide.start_closed": string
"order_guide.template": string
"order_guide.type": string
"order_guide.use_sc_layout": string
"order_guide.vendor": string
"order_guide.visible_bundle": string
"order_guide.visible_guide": string
"order_guide.visible_standalone": string
"order_guide.workflow": string
"order_guide.sys_class_name": string
"order_guide.sys_created_by": string
"order_guide.sys_created_on": string
"order_guide.sys_mod_count": string
"order_guide.sys_name": string
"order_guide.sys_package": string
"order_guide.sys_policy": string
"order_guide.sys_scope": string
"order_guide.sys_updated_by": string
"order_guide.sys_updated_on": string
"order_guide.sys_update_name": string
"request.calendar_stc": string
"request.delivery_address": string
"request.parent_interaction": string
"request.price": string
"request.requested_date": string
"request.requested_for": string
"request.request_state": string
"request.special_instructions": string
"request.stage": string
"request.sys_id": string
"request.active": string
"request.activity_due": string
"request.additional_assignee_list": string
"request.approval": string
"request.approval_history": string
"request.approval_set": string
"request.assigned_to": string
"request.assignment_group": string
"request.business_duration": string
"request.business_service": string
"request.calendar_duration": string
"request.closed_at": string
"request.closed_by": string
"request.close_notes": string
"request.cmdb_ci": string
"request.comments": string
"request.comments_and_work_notes": string
"request.company": string
"request.contact_type": string
"request.contract": string
"request.correlation_display": string
"request.correlation_id": string
"request.delivery_plan": string
"request.delivery_task": string
"request.description": string
"request.due_date": string
"request.escalation": string
"request.expected_start": string
"request.follow_up": string
"request.group_list": string
"request.impact": string
"request.knowledge": string
"request.location": string
"request.made_sla": string
"request.number": string
"request.opened_at": string
"request.opened_by": string
"request.order": string
"request.parent": string
"request.priority": string
"request.reassignment_count": string
"request.service_offering": string
"request.short_description": string
"request.sla_due": string
"request.state": string
"request.sys_class_name": string
"request.sys_created_by": string
"request.sys_created_on": string
"request.sys_domain": string
"request.sys_domain_path": string
"request.sys_mod_count": string
"request.sys_updated_by": string
"request.sys_updated_on": string
"request.time_worked": string
"request.upon_approval": string
"request.upon_reject": string
"request.urgency": string
"request.user_input": string
"request.watch_list": string
"request.work_end": string
"request.work_notes": string
"request.work_notes_list": string
"request.work_start": string
"sc_catalog.active": string
"sc_catalog.background_color": string
"sc_catalog.description": string
"sc_catalog.desktop_continue_shopping": string
"sc_catalog.desktop_home_page": string
"sc_catalog.desktop_image": string
"sc_catalog.editors": string
"sc_catalog.enable_wish_list": string
"sc_catalog.manager": string
"sc_catalog.sys_id": string
"sc_catalog.title": string
"sc_catalog.sys_class_name": string
"sc_catalog.sys_created_by": string
"sc_catalog.sys_created_on": string
"sc_catalog.sys_mod_count": string
"sc_catalog.sys_name": string
"sc_catalog.sys_package": string
"sc_catalog.sys_policy": string
"sc_catalog.sys_scope": string
"sc_catalog.sys_updated_by": string
"sc_catalog.sys_updated_on": string
"sc_catalog.sys_update_name": string
"assigned_to.accumulated_roles": string
"assigned_to.active": string
"assigned_to.avatar": string
"assigned_to.building": string
"assigned_to.calendar_integration": string
"assigned_to.city": string
"assigned_to.company": string
"assigned_to.cost_center": string
"assigned_to.country": string
"assigned_to.date_format": string
"assigned_to.default_perspective": string
"assigned_to.department": string
"assigned_to.email": string
"assigned_to.employee_number": string
"assigned_to.enable_multifactor_authn": string
"assigned_to.failed_attempts": string
"assigned_to.first_name": string
"assigned_to.gender": string
"assigned_to.home_phone": string
"assigned_to.internal_integration_user": string
"assigned_to.introduction": string
"assigned_to.last_login": string
"assigned_to.last_login_time": string
"assigned_to.last_name": string
"assigned_to.ldap_server": string
"assigned_to.location": string
"assigned_to.locked_out": string
"assigned_to.manager": string
"assigned_to.middle_name": string
"assigned_to.mobile_phone": string
"assigned_to.name": string
"assigned_to.notification": string
"assigned_to.password_needs_reset": string
"assigned_to.phone": string
"assigned_to.photo": string
"assigned_to.preferred_language": string
"assigned_to.roles": string
"assigned_to.schedule": string
"assigned_to.source": string
"assigned_to.state": string
"assigned_to.street": string
"assigned_to.sys_class_name": string
"assigned_to.sys_created_by": string
"assigned_to.sys_created_on": string
"assigned_to.sys_domain": string
"assigned_to.sys_domain_path": string
"assigned_to.sys_id": string
"assigned_to.sys_mod_count": string
"assigned_to.sys_updated_by": string
"assigned_to.sys_updated_on": string
"assigned_to.time_format": string
"assigned_to.time_zone": string
"assigned_to.title": string
"assigned_to.user_name": string
"assigned_to.user_password": string
"assigned_to.vip": string
"assigned_to.web_service_access_only": string
"assigned_to.zip": string
"assignment_group.active": string
"assignment_group.cost_center": string
"assignment_group.default_assignee": string
"assignment_group.description": string
"assignment_group.email": string
"assignment_group.exclude_manager": string
"assignment_group.include_members": string
"assignment_group.manager": string
"assignment_group.name": string
"assignment_group.parent": string
"assignment_group.roles": string
"assignment_group.source": string
"assignment_group.sys_created_by": string
"assignment_group.sys_created_on": string
"assignment_group.sys_id": string
"assignment_group.sys_mod_count": string
"assignment_group.sys_updated_by": string
"assignment_group.sys_updated_on": string
"assignment_group.type": string
"business_service.aliases": string
"business_service.asset": string
"business_service.asset_tag": string
"business_service.assigned": string
"business_service.assigned_to": string
"business_service.assignment_group": string
"business_service.attributes": string
"business_service.business_contact": string
"business_service.business_need": string
"business_service.business_relation_manager": string
"business_service.busines_criticality": string
"business_service.can_print": string
"business_service.category": string
"business_service.change_control": string
"business_service.checked_in": string
"business_service.checked_out": string
"business_service.comments": string
"business_service.company": string
"business_service.compatibility_dependencies": string
"business_service.correlation_id": string
"business_service.cost": string
"business_service.cost_cc": string
"business_service.cost_center": string
"business_service.delivery_date": string
"business_service.delivery_manager": string
"business_service.department": string
"business_service.discovery_source": string
"business_service.dns_domain": string
"business_service.due": string
"business_service.due_in": string
"business_service.duplicate_of": string
"business_service.end_date": string
"business_service.fault_count": string
"business_service.first_discovered": string
"business_service.fqdn": string
"business_service.gl_account": string
"business_service.install_date": string
"business_service.install_status": string
"business_service.invoice_number": string
"business_service.ip_address": string
"business_service.justification": string
"business_service.last_discovered": string
"business_service.last_review_date": string
"business_service.lease_id": string
"business_service.location": string
"business_service.mac_address": string
"business_service.maintenance_schedule": string
"business_service.managed_by": string
"business_service.manufacturer": string
"business_service.model_id": string
"business_service.model_number": string
"business_service.monitor": string
"business_service.monitoring_requirements": string
"business_service.name": string
"business_service.number": string
"business_service.operational_status": string
"business_service.order_date": string
"business_service.owned_by": string
"business_service.parent": string
"business_service.po_number": string
"business_service.prerequisites": string
"business_service.price_model": string
"business_service.price_unit": string
"business_service.purchase_date": string
"business_service.schedule": string
"business_service.serial_number": string
"business_service.service_classification": string
"business_service.service_level_requirement": string
"business_service.short_description": string
"business_service.skip_sync": string
"business_service.sla": string
"business_service.start_date": string
"business_service.subcategory": string
"business_service.supported_by": string
"business_service.support_group": string
"business_service.sys_class_name": string
"business_service.sys_class_path": string
"business_service.sys_created_by": string
"business_service.sys_created_on": string
"business_service.sys_domain": string
"business_service.sys_domain_path": string
"business_service.sys_id": string
"business_service.sys_mod_count": string
"business_service.sys_updated_by": string
"business_service.sys_updated_on": string
"business_service.unit_description": string
"business_service.unverified": string
"business_service.used_for": string
"business_service.user_group": string
"business_service.vendor": string
"business_service.version": string
"business_service.warranty_expiration": string
"closed_by.accumulated_roles": string
"closed_by.active": string
"closed_by.avatar": string
"closed_by.building": string
"closed_by.calendar_integration": string
"closed_by.city": string
"closed_by.company": string
"closed_by.cost_center": string
"closed_by.country": string
"closed_by.date_format": string
"closed_by.default_perspective": string
"closed_by.department": string
"closed_by.email": string
"closed_by.employee_number": string
"closed_by.enable_multifactor_authn": string
"closed_by.failed_attempts": string
"closed_by.first_name": string
"closed_by.gender": string
"closed_by.home_phone": string
"closed_by.internal_integration_user": string
"closed_by.introduction": string
"closed_by.last_login": string
"closed_by.last_login_time": string
"closed_by.last_name": string
"closed_by.ldap_server": string
"closed_by.location": string
"closed_by.locked_out": string
"closed_by.manager": string
"closed_by.middle_name": string
"closed_by.mobile_phone": string
"closed_by.name": string
"closed_by.notification": string
"closed_by.password_needs_reset": string
"closed_by.phone": string
"closed_by.photo": string
"closed_by.preferred_language": string
"closed_by.roles": string
"closed_by.schedule": string
"closed_by.source": string
"closed_by.state": string
"closed_by.street": string
"closed_by.sys_class_name": string
"closed_by.sys_created_by": string
"closed_by.sys_created_on": string
"closed_by.sys_domain": string
"closed_by.sys_domain_path": string
"closed_by.sys_id": string
"closed_by.sys_mod_count": string
"closed_by.sys_updated_by": string
"closed_by.sys_updated_on": string
"closed_by.time_format": string
"closed_by.time_zone": string
"closed_by.title": string
"closed_by.user_name": string
"closed_by.user_password": string
"closed_by.vip": string
"closed_by.web_service_access_only": string
"closed_by.zip": string
"cmdb_ci.asset": string
"cmdb_ci.asset_tag": string
"cmdb_ci.assigned": string
"cmdb_ci.assigned_to": string
"cmdb_ci.assignment_group": string
"cmdb_ci.attributes": string
"cmdb_ci.can_print": string
"cmdb_ci.category": string
"cmdb_ci.change_control": string
"cmdb_ci.checked_in": string
"cmdb_ci.checked_out": string
"cmdb_ci.comments": string
"cmdb_ci.company": string
"cmdb_ci.correlation_id": string
"cmdb_ci.cost": string
"cmdb_ci.cost_cc": string
"cmdb_ci.cost_center": string
"cmdb_ci.delivery_date": string
"cmdb_ci.department": string
"cmdb_ci.discovery_source": string
"cmdb_ci.dns_domain": string
"cmdb_ci.due": string
"cmdb_ci.due_in": string
"cmdb_ci.duplicate_of": string
"cmdb_ci.fault_count": string
"cmdb_ci.first_discovered": string
"cmdb_ci.fqdn": string
"cmdb_ci.gl_account": string
"cmdb_ci.install_date": string
"cmdb_ci.install_status": string
"cmdb_ci.invoice_number": string
"cmdb_ci.ip_address": string
"cmdb_ci.justification": string
"cmdb_ci.last_discovered": string
"cmdb_ci.lease_id": string
"cmdb_ci.location": string
"cmdb_ci.mac_address": string
"cmdb_ci.maintenance_schedule": string
"cmdb_ci.managed_by": string
"cmdb_ci.manufacturer": string
"cmdb_ci.model_id": string
"cmdb_ci.model_number": string
"cmdb_ci.monitor": string
"cmdb_ci.name": string
"cmdb_ci.operational_status": string
"cmdb_ci.order_date": string
"cmdb_ci.owned_by": string
"cmdb_ci.po_number": string
"cmdb_ci.purchase_date": string
"cmdb_ci.schedule": string
"cmdb_ci.serial_number": string
"cmdb_ci.short_description": string
"cmdb_ci.skip_sync": string
"cmdb_ci.start_date": string
"cmdb_ci.subcategory": string
"cmdb_ci.supported_by": string
"cmdb_ci.support_group": string
"cmdb_ci.sys_class_name": string
"cmdb_ci.sys_class_path": string
"cmdb_ci.sys_created_by": string
"cmdb_ci.sys_created_on": string
"cmdb_ci.sys_domain": string
"cmdb_ci.sys_domain_path": string
"cmdb_ci.sys_id": string
"cmdb_ci.sys_mod_count": string
"cmdb_ci.sys_updated_by": string
"cmdb_ci.sys_updated_on": string
"cmdb_ci.unverified": string
"cmdb_ci.vendor": string
"cmdb_ci.warranty_expiration": string
"company.apple_icon": string
"company.banner_image": string
"company.banner_image_light": string
"company.banner_text": string
"company.city": string
"company.contact": string
"company.country": string
"company.customer": string
"company.discount": string
"company.fax_phone": string
"company.fiscal_year": string
"company.latitude": string
"company.lat_long_error": string
"company.longitude": string
"company.manufacturer": string
"company.market_cap": string
"company.name": string
"company.notes": string
"company.num_employees": string
"company.parent": string
"company.phone": string
"company.primary": string
"company.profits": string
"company.publicly_traded": string
"company.rank_tier": string
"company.revenue_per_year": string
"company.state": string
"company.stock_price": string
"company.stock_symbol": string
"company.street": string
"company.sys_class_name": string
"company.sys_created_by": string
"company.sys_created_on": string
"company.sys_id": string
"company.sys_mod_count": string
"company.sys_updated_by": string
"company.sys_updated_on": string
"company.theme": string
"company.vendor": string
"company.vendor_manager": string
"company.vendor_type": string
"company.website": string
"company.zip": string
"contract.active": string
"contract.applicable_taxes": string
"contract.application_model": string
"contract.approval_history": string
"contract.approver": string
"contract.business_owner": string
"contract.commitment": string
"contract.contract_administrator": string
"contract.contract_model": string
"contract.cost_adjustment": string
"contract.cost_adjustment_percentage": string
"contract.cost_adjustment_reason": string
"contract.cost_adjustment_type": string
"contract.cost_center": string
"contract.cost_per_unit": string
"contract.covers": string
"contract.customer": string
"contract.description": string
"contract.discount": string
"contract.ends": string
"contract.expiration": string
"contract.invoice_payment_terms": string
"contract.license_quantity_entitled": string
"contract.license_type": string
"contract.lifetime_cost": string
"contract.location": string
"contract.monthly_cost": string
"contract.number": string
"contract.parent_contract": string
"contract.payment_amount": string
"contract.payment_schedule": string
"contract.po_number": string
"contract.process": string
"contract.process_non_contractual_slas": string
"contract.ratecard": string
"contract.renewable": string
"contract.renewal_contact": string
"contract.renewal_date": string
"contract.renewal_end_date": string
"contract.renewal_options": string
"contract.sales_tax": string
"contract.short_description": string
"contract.starts": string
"contract.state": string
"contract.substate": string
"contract.sub_total_cost": string
"contract.sys_class_name": string
"contract.sys_created_by": string
"contract.sys_created_on": string
"contract.sys_domain": string
"contract.sys_domain_path": string
"contract.sys_id": string
"contract.sys_mod_count": string
"contract.sys_updated_by": string
"contract.sys_updated_on": string
"contract.tax_cost": string
"contract.tax_exempt": string
"contract.tax_rate": string
"contract.terms_and_conditions": string
"contract.total_cost": string
"contract.vendor": string
"contract.vendor_account": string
"contract.vendor_contract": string
"contract.yearly_cost": string
"delivery_plan.active": string
"delivery_plan.advanced": string
"delivery_plan.calendar": string
"delivery_plan.condition": string
"delivery_plan.name": string
"delivery_plan.order": string
"delivery_plan.parent_table": string
"delivery_plan.script": string
"delivery_plan.short_description": string
"delivery_plan.sys_id": string
"delivery_plan.task_table": string
"delivery_plan.total_delivery_time": string
"delivery_plan.sys_class_name": string
"delivery_plan.sys_created_by": string
"delivery_plan.sys_created_on": string
"delivery_plan.sys_mod_count": string
"delivery_plan.sys_name": string
"delivery_plan.sys_package": string
"delivery_plan.sys_policy": string
"delivery_plan.sys_scope": string
"delivery_plan.sys_updated_by": string
"delivery_plan.sys_updated_on": string
"delivery_plan.sys_update_name": string
"delivery_task.assigned_to": string
"delivery_task.condition": string
"delivery_task.condition_script": string
"delivery_task.delivery_plan": string
"delivery_task.delivery_time": string
"delivery_task.generation_script": string
"delivery_task.group": string
"delivery_task.instructions": string
"delivery_task.name": string
"delivery_task.order": string
"delivery_task.short_description": string
"delivery_task.sla": string
"delivery_task.sys_id": string
"delivery_task.work_notes": string
"delivery_task.sys_class_name": string
"delivery_task.sys_created_by": string
"delivery_task.sys_created_on": string
"delivery_task.sys_mod_count": string
"delivery_task.sys_name": string
"delivery_task.sys_package": string
"delivery_task.sys_policy": string
"delivery_task.sys_scope": string
"delivery_task.sys_updated_by": string
"delivery_task.sys_updated_on": string
"delivery_task.sys_update_name": string
"location.city": string
"location.company": string
"location.contact": string
"location.country": string
"location.fax_phone": string
"location.full_name": string
"location.latitude": string
"location.lat_long_error": string
"location.longitude": string
"location.name": string
"location.parent": string
"location.phone": string
"location.phone_territory": string
"location.state": string
"location.stock_room": string
"location.street": string
"location.sys_created_by": string
"location.sys_created_on": string
"location.sys_id": string
"location.sys_mod_count": string
"location.sys_updated_by": string
"location.sys_updated_on": string
"location.time_zone": string
"location.zip": string
"opened_by.accumulated_roles": string
"opened_by.active": string
"opened_by.avatar": string
"opened_by.building": string
"opened_by.calendar_integration": string
"opened_by.city": string
"opened_by.company": string
"opened_by.cost_center": string
"opened_by.country": string
"opened_by.date_format": string
"opened_by.default_perspective": string
"opened_by.department": string
"opened_by.email": string
"opened_by.employee_number": string
"opened_by.enable_multifactor_authn": string
"opened_by.failed_attempts": string
"opened_by.first_name": string
"opened_by.gender": string
"opened_by.home_phone": string
"opened_by.internal_integration_user": string
"opened_by.introduction": string
"opened_by.last_login": string
"opened_by.last_login_time": string
"opened_by.last_name": string
"opened_by.ldap_server": string
"opened_by.location": string
"opened_by.locked_out": string
"opened_by.manager": string
"opened_by.middle_name": string
"opened_by.mobile_phone": string
"opened_by.name": string
"opened_by.notification": string
"opened_by.password_needs_reset": string
"opened_by.phone": string
"opened_by.photo": string
"opened_by.preferred_language": string
"opened_by.roles": string
"opened_by.schedule": string
"opened_by.source": string
"opened_by.state": string
"opened_by.street": string
"opened_by.sys_class_name": string
"opened_by.sys_created_by": string
"opened_by.sys_created_on": string
"opened_by.sys_domain": string
"opened_by.sys_domain_path": string
"opened_by.sys_id": string
"opened_by.sys_mod_count": string
"opened_by.sys_updated_by": string
"opened_by.sys_updated_on": string
"opened_by.time_format": string
"opened_by.time_zone": string
"opened_by.title": string
"opened_by.user_name": string
"opened_by.user_password": string
"opened_by.vip": string
"opened_by.web_service_access_only": string
"opened_by.zip": string
"parent.active": string
"parent.activity_due": string
"parent.additional_assignee_list": string
"parent.approval": string
"parent.approval_history": string
"parent.approval_set": string
"parent.assigned_to": string
"parent.assignment_group": string
"parent.business_duration": string
"parent.business_service": string
"parent.calendar_duration": string
"parent.closed_at": string
"parent.closed_by": string
"parent.close_notes": string
"parent.cmdb_ci": string
"parent.comments": string
"parent.comments_and_work_notes": string
"parent.company": string
"parent.contact_type": string
"parent.contract": string
"parent.correlation_display": string
"parent.correlation_id": string
"parent.delivery_plan": string
"parent.delivery_task": string
"parent.description": string
"parent.due_date": string
"parent.escalation": string
"parent.expected_start": string
"parent.follow_up": string
"parent.group_list": string
"parent.impact": string
"parent.knowledge": string
"parent.location": string
"parent.made_sla": string
"parent.number": string
"parent.opened_at": string
"parent.opened_by": string
"parent.order": string
"parent.parent": string
"parent.priority": string
"parent.reassignment_count": string
"parent.service_offering": string
"parent.short_description": string
"parent.sla_due": string
"parent.state": string
"parent.sys_class_name": string
"parent.sys_created_by": string
"parent.sys_created_on": string
"parent.sys_domain": string
"parent.sys_domain_path": string
"parent.sys_id": string
"parent.sys_mod_count": string
"parent.sys_updated_by": string
"parent.sys_updated_on": string
"parent.time_worked": string
"parent.upon_approval": string
"parent.upon_reject": string
"parent.urgency": string
"parent.user_input": string
"parent.watch_list": string
"parent.work_end": string
"parent.work_notes": string
"parent.work_notes_list": string
"parent.work_start": string
"service_offering.aliases": string
"service_offering.asset": string
"service_offering.asset_tag": string
"service_offering.assigned": string
"service_offering.assigned_to": string
"service_offering.assignment_group": string
"service_offering.attributes": string
"service_offering.billing": string
"service_offering.business_contact": string
"service_offering.business_need": string
"service_offering.business_relation_manager": string
"service_offering.busines_criticality": string
"service_offering.can_print": string
"service_offering.category": string
"service_offering.change_control": string
"service_offering.checked_in": string
"service_offering.checked_out": string
"service_offering.comments": string
"service_offering.company": string
"service_offering.compatibility_dependencies": string
"service_offering.contract": string
"service_offering.correlation_id": string
"service_offering.cost": string
"service_offering.cost_cc": string
"service_offering.cost_center": string
"service_offering.delivery_date": string
"service_offering.delivery_manager": string
"service_offering.department": string
"service_offering.description": string
"service_offering.discovery_source": string
"service_offering.dns_domain": string
"service_offering.due": string
"service_offering.due_in": string
"service_offering.duplicate_of": string
"service_offering.end_date": string
"service_offering.fault_count": string
"service_offering.first_discovered": string
"service_offering.fqdn": string
"service_offering.gl_account": string
"service_offering.install_date": string
"service_offering.install_status": string
"service_offering.invoice_number": string
"service_offering.ip_address": string
"service_offering.justification": string
"service_offering.last_discovered": string
"service_offering.last_review_date": string
"service_offering.lease_id": string
"service_offering.location": string
"service_offering.mac_address": string
"service_offering.maintenance_schedule": string
"service_offering.managed_by": string
"service_offering.manufacturer": string
"service_offering.model_id": string
"service_offering.model_number": string
"service_offering.monitor": string
"service_offering.monitoring_requirements": string
"service_offering.name": string
"service_offering.number": string
"service_offering.operational_status": string
"service_offering.order": string
"service_offering.order_date": string
"service_offering.owned_by": string
"service_offering.parent": string
"service_offering.po_number": string
"service_offering.prerequisites": string
"service_offering.price": string
"service_offering.price_model": string
"service_offering.price_unit": string
"service_offering.purchase_date": string
"service_offering.schedule": string
"service_offering.serial_number": string
"service_offering.service_classification": string
"service_offering.service_level_requirement": string
"service_offering.short_description": string
"service_offering.skip_sync": string
"service_offering.sla": string
"service_offering.start_date": string
"service_offering.subcategory": string
"service_offering.supported_by": string
"service_offering.support_group": string
"service_offering.sys_class_name": string
"service_offering.sys_class_path": string
"service_offering.sys_created_by": string
"service_offering.sys_created_on": string
"service_offering.sys_domain": string
"service_offering.sys_domain_path": string
"service_offering.sys_id": string
"service_offering.sys_mod_count": string
"service_offering.sys_updated_by": string
"service_offering.sys_updated_on": string
"service_offering.technical_contact": string
"service_offering.unit_description": string
"service_offering.unverified": string
"service_offering.used_for": string
"service_offering.user_group": string
"service_offering.vendor": string
"service_offering.version": string
"service_offering.warranty_expiration": string;
      }
    }
   