declare interface sc_request {
      calendar_stc: GlideElement<sc_request, glideElementType.defaultType>;
delivery_address: GlideElement<sc_request, glideElementType.defaultType>;
parent_interaction: GlideElement<sc_request, glideElementType.g_reference<interaction>>;
price: GlideElement<sc_request, glideElementType.g_currency>;
requested_date: GlideElement<sc_request, glideElementType.g_glide_date>;
requested_for: GlideElement<sc_request, glideElementType.g_reference<sys_user>>;
request_state: GlideElement<sc_request, glideElementType.defaultType>;
special_instructions: GlideElement<sc_request, glideElementType.defaultType>;
stage: GlideElement<sc_request, glideElementType.defaultType>;
sys_id: GlideElement<sc_request, glideElementType.defaultType>;
active: GlideElement<sc_request, glideElementType.g_boolean>;
activity_due: GlideElement<sc_request, glideElementType.defaultType>;
additional_assignee_list: GlideElement<sc_request, glideElementType.defaultType>;
approval: GlideElement<sc_request, glideElementType.defaultType>;
approval_history: GlideElement<sc_request, glideElementType.defaultType>;
approval_set: GlideElement<sc_request, glideElementType.g_glide_date_time>;
assigned_to: GlideElement<sc_request, glideElementType.g_reference<sys_user>>;
assignment_group: GlideElement<sc_request, glideElementType.g_reference<sys_user_group>>;
business_duration: GlideElement<sc_request, glideElementType.defaultType>;
business_service: GlideElement<sc_request, glideElementType.g_reference<cmdb_ci_service>>;
calendar_duration: GlideElement<sc_request, glideElementType.defaultType>;
closed_at: GlideElement<sc_request, glideElementType.g_glide_date_time>;
closed_by: GlideElement<sc_request, glideElementType.g_reference<sys_user>>;
close_notes: GlideElement<sc_request, glideElementType.defaultType>;
cmdb_ci: GlideElement<sc_request, glideElementType.g_reference<cmdb_ci>>;
comments: GlideElement<sc_request, glideElementType.defaultType>;
comments_and_work_notes: GlideElement<sc_request, glideElementType.defaultType>;
company: GlideElement<sc_request, glideElementType.g_reference<core_company>>;
contact_type: GlideElement<sc_request, glideElementType.defaultType>;
contract: GlideElement<sc_request, glideElementType.g_reference<ast_contract>>;
correlation_display: GlideElement<sc_request, glideElementType.defaultType>;
correlation_id: GlideElement<sc_request, glideElementType.defaultType>;
delivery_plan: GlideElement<sc_request, glideElementType.g_reference<sc_cat_item_delivery_plan>>;
delivery_task: GlideElement<sc_request, glideElementType.g_reference<sc_cat_item_delivery_task>>;
description: GlideElement<sc_request, glideElementType.defaultType>;
due_date: GlideElement<sc_request, glideElementType.g_glide_date_time>;
escalation: GlideElement<sc_request, glideElementType.defaultType>;
expected_start: GlideElement<sc_request, glideElementType.g_glide_date_time>;
follow_up: GlideElement<sc_request, glideElementType.g_glide_date_time>;
group_list: GlideElement<sc_request, glideElementType.defaultType>;
impact: GlideElement<sc_request, glideElementType.defaultType>;
knowledge: GlideElement<sc_request, glideElementType.g_boolean>;
location: GlideElement<sc_request, glideElementType.g_reference<cmn_location>>;
made_sla: GlideElement<sc_request, glideElementType.g_boolean>;
number: GlideElement<sc_request, glideElementType.defaultType>;
opened_at: GlideElement<sc_request, glideElementType.g_glide_date_time>;
opened_by: GlideElement<sc_request, glideElementType.g_reference<sys_user>>;
order: GlideElement<sc_request, glideElementType.defaultType>;
parent: GlideElement<sc_request, glideElementType.g_reference<task>>;
priority: GlideElement<sc_request, glideElementType.defaultType>;
reassignment_count: GlideElement<sc_request, glideElementType.defaultType>;
service_offering: GlideElement<sc_request, glideElementType.g_reference<service_offering>>;
short_description: GlideElement<sc_request, glideElementType.defaultType>;
sla_due: GlideElement<sc_request, glideElementType.defaultType>;
state: GlideElement<sc_request, glideElementType.defaultType>;
sys_class_name: GlideElement<sc_request, glideElementType.defaultType>;
sys_created_by: GlideElement<sc_request, glideElementType.defaultType>;
sys_created_on: GlideElement<sc_request, glideElementType.g_glide_date_time>;
sys_domain: GlideElement<sc_request, glideElementType.defaultType>;
sys_domain_path: GlideElement<sc_request, glideElementType.defaultType>;
sys_mod_count: GlideElement<sc_request, glideElementType.defaultType>;
sys_updated_by: GlideElement<sc_request, glideElementType.defaultType>;
sys_updated_on: GlideElement<sc_request, glideElementType.g_glide_date_time>;
time_worked: GlideElement<sc_request, glideElementType.defaultType>;
upon_approval: GlideElement<sc_request, glideElementType.defaultType>;
upon_reject: GlideElement<sc_request, glideElementType.defaultType>;
urgency: GlideElement<sc_request, glideElementType.defaultType>;
user_input: GlideElement<sc_request, glideElementType.defaultType>;
watch_list: GlideElement<sc_request, glideElementType.defaultType>;
work_end: GlideElement<sc_request, glideElementType.g_glide_date_time>;
work_notes: GlideElement<sc_request, glideElementType.defaultType>;
work_notes_list: GlideElement<sc_request, glideElementType.defaultType>;
work_start: GlideElement<sc_request, glideElementType.g_glide_date_time>;
      _referenceKeys: never | {
        "parent_interaction.active": string
"parent_interaction.assigned_to": string
"parent_interaction.channel_metadata_document": string
"parent_interaction.channel_metadata_table": string
"parent_interaction.closed_at": string
"parent_interaction.closed_by": string
"parent_interaction.context_document": string
"parent_interaction.context_table": string
"parent_interaction.direction": string
"parent_interaction.duration": string
"parent_interaction.location": string
"parent_interaction.number": string
"parent_interaction.opened_at": string
"parent_interaction.opened_for": string
"parent_interaction.parent": string
"parent_interaction.short_description": string
"parent_interaction.state": string
"parent_interaction.sys_class_name": string
"parent_interaction.sys_created_by": string
"parent_interaction.sys_created_on": string
"parent_interaction.sys_domain": string
"parent_interaction.sys_domain_path": string
"parent_interaction.sys_id": string
"parent_interaction.sys_mod_count": string
"parent_interaction.sys_updated_by": string
"parent_interaction.sys_updated_on": string
"parent_interaction.transcript": string
"parent_interaction.type": string
"parent_interaction.verified": string
"parent_interaction.wait_time": string
"parent_interaction.work_notes": string
"requested_for.accumulated_roles": string
"requested_for.active": string
"requested_for.avatar": string
"requested_for.building": string
"requested_for.calendar_integration": string
"requested_for.city": string
"requested_for.company": string
"requested_for.cost_center": string
"requested_for.country": string
"requested_for.date_format": string
"requested_for.default_perspective": string
"requested_for.department": string
"requested_for.email": string
"requested_for.employee_number": string
"requested_for.enable_multifactor_authn": string
"requested_for.failed_attempts": string
"requested_for.first_name": string
"requested_for.gender": string
"requested_for.home_phone": string
"requested_for.internal_integration_user": string
"requested_for.introduction": string
"requested_for.last_login": string
"requested_for.last_login_time": string
"requested_for.last_name": string
"requested_for.ldap_server": string
"requested_for.location": string
"requested_for.locked_out": string
"requested_for.manager": string
"requested_for.middle_name": string
"requested_for.mobile_phone": string
"requested_for.name": string
"requested_for.notification": string
"requested_for.password_needs_reset": string
"requested_for.phone": string
"requested_for.photo": string
"requested_for.preferred_language": string
"requested_for.roles": string
"requested_for.schedule": string
"requested_for.source": string
"requested_for.state": string
"requested_for.street": string
"requested_for.sys_class_name": string
"requested_for.sys_created_by": string
"requested_for.sys_created_on": string
"requested_for.sys_domain": string
"requested_for.sys_domain_path": string
"requested_for.sys_id": string
"requested_for.sys_mod_count": string
"requested_for.sys_updated_by": string
"requested_for.sys_updated_on": string
"requested_for.time_format": string
"requested_for.time_zone": string
"requested_for.title": string
"requested_for.user_name": string
"requested_for.user_password": string
"requested_for.vip": string
"requested_for.web_service_access_only": string
"requested_for.zip": string
"assigned_to.accumulated_roles": string
"assigned_to.active": string
"assigned_to.avatar": string
"assigned_to.building": string
"assigned_to.calendar_integration": string
"assigned_to.city": string
"assigned_to.company": string
"assigned_to.cost_center": string
"assigned_to.country": string
"assigned_to.date_format": string
"assigned_to.default_perspective": string
"assigned_to.department": string
"assigned_to.email": string
"assigned_to.employee_number": string
"assigned_to.enable_multifactor_authn": string
"assigned_to.failed_attempts": string
"assigned_to.first_name": string
"assigned_to.gender": string
"assigned_to.home_phone": string
"assigned_to.internal_integration_user": string
"assigned_to.introduction": string
"assigned_to.last_login": string
"assigned_to.last_login_time": string
"assigned_to.last_name": string
"assigned_to.ldap_server": string
"assigned_to.location": string
"assigned_to.locked_out": string
"assigned_to.manager": string
"assigned_to.middle_name": string
"assigned_to.mobile_phone": string
"assigned_to.name": string
"assigned_to.notification": string
"assigned_to.password_needs_reset": string
"assigned_to.phone": string
"assigned_to.photo": string
"assigned_to.preferred_language": string
"assigned_to.roles": string
"assigned_to.schedule": string
"assigned_to.source": string
"assigned_to.state": string
"assigned_to.street": string
"assigned_to.sys_class_name": string
"assigned_to.sys_created_by": string
"assigned_to.sys_created_on": string
"assigned_to.sys_domain": string
"assigned_to.sys_domain_path": string
"assigned_to.sys_id": string
"assigned_to.sys_mod_count": string
"assigned_to.sys_updated_by": string
"assigned_to.sys_updated_on": string
"assigned_to.time_format": string
"assigned_to.time_zone": string
"assigned_to.title": string
"assigned_to.user_name": string
"assigned_to.user_password": string
"assigned_to.vip": string
"assigned_to.web_service_access_only": string
"assigned_to.zip": string
"assignment_group.active": string
"assignment_group.cost_center": string
"assignment_group.default_assignee": string
"assignment_group.description": string
"assignment_group.email": string
"assignment_group.exclude_manager": string
"assignment_group.include_members": string
"assignment_group.manager": string
"assignment_group.name": string
"assignment_group.parent": string
"assignment_group.roles": string
"assignment_group.source": string
"assignment_group.sys_created_by": string
"assignment_group.sys_created_on": string
"assignment_group.sys_id": string
"assignment_group.sys_mod_count": string
"assignment_group.sys_updated_by": string
"assignment_group.sys_updated_on": string
"assignment_group.type": string
"business_service.aliases": string
"business_service.asset": string
"business_service.asset_tag": string
"business_service.assigned": string
"business_service.assigned_to": string
"business_service.assignment_group": string
"business_service.attributes": string
"business_service.business_contact": string
"business_service.business_need": string
"business_service.business_relation_manager": string
"business_service.busines_criticality": string
"business_service.can_print": string
"business_service.category": string
"business_service.change_control": string
"business_service.checked_in": string
"business_service.checked_out": string
"business_service.comments": string
"business_service.company": string
"business_service.compatibility_dependencies": string
"business_service.correlation_id": string
"business_service.cost": string
"business_service.cost_cc": string
"business_service.cost_center": string
"business_service.delivery_date": string
"business_service.delivery_manager": string
"business_service.department": string
"business_service.discovery_source": string
"business_service.dns_domain": string
"business_service.due": string
"business_service.due_in": string
"business_service.duplicate_of": string
"business_service.end_date": string
"business_service.fault_count": string
"business_service.first_discovered": string
"business_service.fqdn": string
"business_service.gl_account": string
"business_service.install_date": string
"business_service.install_status": string
"business_service.invoice_number": string
"business_service.ip_address": string
"business_service.justification": string
"business_service.last_discovered": string
"business_service.last_review_date": string
"business_service.lease_id": string
"business_service.location": string
"business_service.mac_address": string
"business_service.maintenance_schedule": string
"business_service.managed_by": string
"business_service.manufacturer": string
"business_service.model_id": string
"business_service.model_number": string
"business_service.monitor": string
"business_service.monitoring_requirements": string
"business_service.name": string
"business_service.number": string
"business_service.operational_status": string
"business_service.order_date": string
"business_service.owned_by": string
"business_service.parent": string
"business_service.po_number": string
"business_service.prerequisites": string
"business_service.price_model": string
"business_service.price_unit": string
"business_service.purchase_date": string
"business_service.schedule": string
"business_service.serial_number": string
"business_service.service_classification": string
"business_service.service_level_requirement": string
"business_service.short_description": string
"business_service.skip_sync": string
"business_service.sla": string
"business_service.start_date": string
"business_service.subcategory": string
"business_service.supported_by": string
"business_service.support_group": string
"business_service.sys_class_name": string
"business_service.sys_class_path": string
"business_service.sys_created_by": string
"business_service.sys_created_on": string
"business_service.sys_domain": string
"business_service.sys_domain_path": string
"business_service.sys_id": string
"business_service.sys_mod_count": string
"business_service.sys_updated_by": string
"business_service.sys_updated_on": string
"business_service.unit_description": string
"business_service.unverified": string
"business_service.used_for": string
"business_service.user_group": string
"business_service.vendor": string
"business_service.version": string
"business_service.warranty_expiration": string
"closed_by.accumulated_roles": string
"closed_by.active": string
"closed_by.avatar": string
"closed_by.building": string
"closed_by.calendar_integration": string
"closed_by.city": string
"closed_by.company": string
"closed_by.cost_center": string
"closed_by.country": string
"closed_by.date_format": string
"closed_by.default_perspective": string
"closed_by.department": string
"closed_by.email": string
"closed_by.employee_number": string
"closed_by.enable_multifactor_authn": string
"closed_by.failed_attempts": string
"closed_by.first_name": string
"closed_by.gender": string
"closed_by.home_phone": string
"closed_by.internal_integration_user": string
"closed_by.introduction": string
"closed_by.last_login": string
"closed_by.last_login_time": string
"closed_by.last_name": string
"closed_by.ldap_server": string
"closed_by.location": string
"closed_by.locked_out": string
"closed_by.manager": string
"closed_by.middle_name": string
"closed_by.mobile_phone": string
"closed_by.name": string
"closed_by.notification": string
"closed_by.password_needs_reset": string
"closed_by.phone": string
"closed_by.photo": string
"closed_by.preferred_language": string
"closed_by.roles": string
"closed_by.schedule": string
"closed_by.source": string
"closed_by.state": string
"closed_by.street": string
"closed_by.sys_class_name": string
"closed_by.sys_created_by": string
"closed_by.sys_created_on": string
"closed_by.sys_domain": string
"closed_by.sys_domain_path": string
"closed_by.sys_id": string
"closed_by.sys_mod_count": string
"closed_by.sys_updated_by": string
"closed_by.sys_updated_on": string
"closed_by.time_format": string
"closed_by.time_zone": string
"closed_by.title": string
"closed_by.user_name": string
"closed_by.user_password": string
"closed_by.vip": string
"closed_by.web_service_access_only": string
"closed_by.zip": string
"cmdb_ci.asset": string
"cmdb_ci.asset_tag": string
"cmdb_ci.assigned": string
"cmdb_ci.assigned_to": string
"cmdb_ci.assignment_group": string
"cmdb_ci.attributes": string
"cmdb_ci.can_print": string
"cmdb_ci.category": string
"cmdb_ci.change_control": string
"cmdb_ci.checked_in": string
"cmdb_ci.checked_out": string
"cmdb_ci.comments": string
"cmdb_ci.company": string
"cmdb_ci.correlation_id": string
"cmdb_ci.cost": string
"cmdb_ci.cost_cc": string
"cmdb_ci.cost_center": string
"cmdb_ci.delivery_date": string
"cmdb_ci.department": string
"cmdb_ci.discovery_source": string
"cmdb_ci.dns_domain": string
"cmdb_ci.due": string
"cmdb_ci.due_in": string
"cmdb_ci.duplicate_of": string
"cmdb_ci.fault_count": string
"cmdb_ci.first_discovered": string
"cmdb_ci.fqdn": string
"cmdb_ci.gl_account": string
"cmdb_ci.install_date": string
"cmdb_ci.install_status": string
"cmdb_ci.invoice_number": string
"cmdb_ci.ip_address": string
"cmdb_ci.justification": string
"cmdb_ci.last_discovered": string
"cmdb_ci.lease_id": string
"cmdb_ci.location": string
"cmdb_ci.mac_address": string
"cmdb_ci.maintenance_schedule": string
"cmdb_ci.managed_by": string
"cmdb_ci.manufacturer": string
"cmdb_ci.model_id": string
"cmdb_ci.model_number": string
"cmdb_ci.monitor": string
"cmdb_ci.name": string
"cmdb_ci.operational_status": string
"cmdb_ci.order_date": string
"cmdb_ci.owned_by": string
"cmdb_ci.po_number": string
"cmdb_ci.purchase_date": string
"cmdb_ci.schedule": string
"cmdb_ci.serial_number": string
"cmdb_ci.short_description": string
"cmdb_ci.skip_sync": string
"cmdb_ci.start_date": string
"cmdb_ci.subcategory": string
"cmdb_ci.supported_by": string
"cmdb_ci.support_group": string
"cmdb_ci.sys_class_name": string
"cmdb_ci.sys_class_path": string
"cmdb_ci.sys_created_by": string
"cmdb_ci.sys_created_on": string
"cmdb_ci.sys_domain": string
"cmdb_ci.sys_domain_path": string
"cmdb_ci.sys_id": string
"cmdb_ci.sys_mod_count": string
"cmdb_ci.sys_updated_by": string
"cmdb_ci.sys_updated_on": string
"cmdb_ci.unverified": string
"cmdb_ci.vendor": string
"cmdb_ci.warranty_expiration": string
"company.apple_icon": string
"company.banner_image": string
"company.banner_image_light": string
"company.banner_text": string
"company.city": string
"company.contact": string
"company.country": string
"company.customer": string
"company.discount": string
"company.fax_phone": string
"company.fiscal_year": string
"company.latitude": string
"company.lat_long_error": string
"company.longitude": string
"company.manufacturer": string
"company.market_cap": string
"company.name": string
"company.notes": string
"company.num_employees": string
"company.parent": string
"company.phone": string
"company.primary": string
"company.profits": string
"company.publicly_traded": string
"company.rank_tier": string
"company.revenue_per_year": string
"company.state": string
"company.stock_price": string
"company.stock_symbol": string
"company.street": string
"company.sys_class_name": string
"company.sys_created_by": string
"company.sys_created_on": string
"company.sys_id": string
"company.sys_mod_count": string
"company.sys_updated_by": string
"company.sys_updated_on": string
"company.theme": string
"company.vendor": string
"company.vendor_manager": string
"company.vendor_type": string
"company.website": string
"company.zip": string
"contract.active": string
"contract.applicable_taxes": string
"contract.application_model": string
"contract.approval_history": string
"contract.approver": string
"contract.business_owner": string
"contract.commitment": string
"contract.contract_administrator": string
"contract.contract_model": string
"contract.cost_adjustment": string
"contract.cost_adjustment_percentage": string
"contract.cost_adjustment_reason": string
"contract.cost_adjustment_type": string
"contract.cost_center": string
"contract.cost_per_unit": string
"contract.covers": string
"contract.customer": string
"contract.description": string
"contract.discount": string
"contract.ends": string
"contract.expiration": string
"contract.invoice_payment_terms": string
"contract.license_quantity_entitled": string
"contract.license_type": string
"contract.lifetime_cost": string
"contract.location": string
"contract.monthly_cost": string
"contract.number": string
"contract.parent_contract": string
"contract.payment_amount": string
"contract.payment_schedule": string
"contract.po_number": string
"contract.process": string
"contract.process_non_contractual_slas": string
"contract.ratecard": string
"contract.renewable": string
"contract.renewal_contact": string
"contract.renewal_date": string
"contract.renewal_end_date": string
"contract.renewal_options": string
"contract.sales_tax": string
"contract.short_description": string
"contract.starts": string
"contract.state": string
"contract.substate": string
"contract.sub_total_cost": string
"contract.sys_class_name": string
"contract.sys_created_by": string
"contract.sys_created_on": string
"contract.sys_domain": string
"contract.sys_domain_path": string
"contract.sys_id": string
"contract.sys_mod_count": string
"contract.sys_updated_by": string
"contract.sys_updated_on": string
"contract.tax_cost": string
"contract.tax_exempt": string
"contract.tax_rate": string
"contract.terms_and_conditions": string
"contract.total_cost": string
"contract.vendor": string
"contract.vendor_account": string
"contract.vendor_contract": string
"contract.yearly_cost": string
"delivery_plan.active": string
"delivery_plan.advanced": string
"delivery_plan.calendar": string
"delivery_plan.condition": string
"delivery_plan.name": string
"delivery_plan.order": string
"delivery_plan.parent_table": string
"delivery_plan.script": string
"delivery_plan.short_description": string
"delivery_plan.sys_id": string
"delivery_plan.task_table": string
"delivery_plan.total_delivery_time": string
"delivery_plan.sys_class_name": string
"delivery_plan.sys_created_by": string
"delivery_plan.sys_created_on": string
"delivery_plan.sys_mod_count": string
"delivery_plan.sys_name": string
"delivery_plan.sys_package": string
"delivery_plan.sys_policy": string
"delivery_plan.sys_scope": string
"delivery_plan.sys_updated_by": string
"delivery_plan.sys_updated_on": string
"delivery_plan.sys_update_name": string
"delivery_task.assigned_to": string
"delivery_task.condition": string
"delivery_task.condition_script": string
"delivery_task.delivery_plan": string
"delivery_task.delivery_time": string
"delivery_task.generation_script": string
"delivery_task.group": string
"delivery_task.instructions": string
"delivery_task.name": string
"delivery_task.order": string
"delivery_task.short_description": string
"delivery_task.sla": string
"delivery_task.sys_id": string
"delivery_task.work_notes": string
"delivery_task.sys_class_name": string
"delivery_task.sys_created_by": string
"delivery_task.sys_created_on": string
"delivery_task.sys_mod_count": string
"delivery_task.sys_name": string
"delivery_task.sys_package": string
"delivery_task.sys_policy": string
"delivery_task.sys_scope": string
"delivery_task.sys_updated_by": string
"delivery_task.sys_updated_on": string
"delivery_task.sys_update_name": string
"location.city": string
"location.company": string
"location.contact": string
"location.country": string
"location.fax_phone": string
"location.full_name": string
"location.latitude": string
"location.lat_long_error": string
"location.longitude": string
"location.name": string
"location.parent": string
"location.phone": string
"location.phone_territory": string
"location.state": string
"location.stock_room": string
"location.street": string
"location.sys_created_by": string
"location.sys_created_on": string
"location.sys_id": string
"location.sys_mod_count": string
"location.sys_updated_by": string
"location.sys_updated_on": string
"location.time_zone": string
"location.zip": string
"opened_by.accumulated_roles": string
"opened_by.active": string
"opened_by.avatar": string
"opened_by.building": string
"opened_by.calendar_integration": string
"opened_by.city": string
"opened_by.company": string
"opened_by.cost_center": string
"opened_by.country": string
"opened_by.date_format": string
"opened_by.default_perspective": string
"opened_by.department": string
"opened_by.email": string
"opened_by.employee_number": string
"opened_by.enable_multifactor_authn": string
"opened_by.failed_attempts": string
"opened_by.first_name": string
"opened_by.gender": string
"opened_by.home_phone": string
"opened_by.internal_integration_user": string
"opened_by.introduction": string
"opened_by.last_login": string
"opened_by.last_login_time": string
"opened_by.last_name": string
"opened_by.ldap_server": string
"opened_by.location": string
"opened_by.locked_out": string
"opened_by.manager": string
"opened_by.middle_name": string
"opened_by.mobile_phone": string
"opened_by.name": string
"opened_by.notification": string
"opened_by.password_needs_reset": string
"opened_by.phone": string
"opened_by.photo": string
"opened_by.preferred_language": string
"opened_by.roles": string
"opened_by.schedule": string
"opened_by.source": string
"opened_by.state": string
"opened_by.street": string
"opened_by.sys_class_name": string
"opened_by.sys_created_by": string
"opened_by.sys_created_on": string
"opened_by.sys_domain": string
"opened_by.sys_domain_path": string
"opened_by.sys_id": string
"opened_by.sys_mod_count": string
"opened_by.sys_updated_by": string
"opened_by.sys_updated_on": string
"opened_by.time_format": string
"opened_by.time_zone": string
"opened_by.title": string
"opened_by.user_name": string
"opened_by.user_password": string
"opened_by.vip": string
"opened_by.web_service_access_only": string
"opened_by.zip": string
"parent.active": string
"parent.activity_due": string
"parent.additional_assignee_list": string
"parent.approval": string
"parent.approval_history": string
"parent.approval_set": string
"parent.assigned_to": string
"parent.assignment_group": string
"parent.business_duration": string
"parent.business_service": string
"parent.calendar_duration": string
"parent.closed_at": string
"parent.closed_by": string
"parent.close_notes": string
"parent.cmdb_ci": string
"parent.comments": string
"parent.comments_and_work_notes": string
"parent.company": string
"parent.contact_type": string
"parent.contract": string
"parent.correlation_display": string
"parent.correlation_id": string
"parent.delivery_plan": string
"parent.delivery_task": string
"parent.description": string
"parent.due_date": string
"parent.escalation": string
"parent.expected_start": string
"parent.follow_up": string
"parent.group_list": string
"parent.impact": string
"parent.knowledge": string
"parent.location": string
"parent.made_sla": string
"parent.number": string
"parent.opened_at": string
"parent.opened_by": string
"parent.order": string
"parent.parent": string
"parent.priority": string
"parent.reassignment_count": string
"parent.service_offering": string
"parent.short_description": string
"parent.sla_due": string
"parent.state": string
"parent.sys_class_name": string
"parent.sys_created_by": string
"parent.sys_created_on": string
"parent.sys_domain": string
"parent.sys_domain_path": string
"parent.sys_id": string
"parent.sys_mod_count": string
"parent.sys_updated_by": string
"parent.sys_updated_on": string
"parent.time_worked": string
"parent.upon_approval": string
"parent.upon_reject": string
"parent.urgency": string
"parent.user_input": string
"parent.watch_list": string
"parent.work_end": string
"parent.work_notes": string
"parent.work_notes_list": string
"parent.work_start": string
"service_offering.aliases": string
"service_offering.asset": string
"service_offering.asset_tag": string
"service_offering.assigned": string
"service_offering.assigned_to": string
"service_offering.assignment_group": string
"service_offering.attributes": string
"service_offering.billing": string
"service_offering.business_contact": string
"service_offering.business_need": string
"service_offering.business_relation_manager": string
"service_offering.busines_criticality": string
"service_offering.can_print": string
"service_offering.category": string
"service_offering.change_control": string
"service_offering.checked_in": string
"service_offering.checked_out": string
"service_offering.comments": string
"service_offering.company": string
"service_offering.compatibility_dependencies": string
"service_offering.contract": string
"service_offering.correlation_id": string
"service_offering.cost": string
"service_offering.cost_cc": string
"service_offering.cost_center": string
"service_offering.delivery_date": string
"service_offering.delivery_manager": string
"service_offering.department": string
"service_offering.description": string
"service_offering.discovery_source": string
"service_offering.dns_domain": string
"service_offering.due": string
"service_offering.due_in": string
"service_offering.duplicate_of": string
"service_offering.end_date": string
"service_offering.fault_count": string
"service_offering.first_discovered": string
"service_offering.fqdn": string
"service_offering.gl_account": string
"service_offering.install_date": string
"service_offering.install_status": string
"service_offering.invoice_number": string
"service_offering.ip_address": string
"service_offering.justification": string
"service_offering.last_discovered": string
"service_offering.last_review_date": string
"service_offering.lease_id": string
"service_offering.location": string
"service_offering.mac_address": string
"service_offering.maintenance_schedule": string
"service_offering.managed_by": string
"service_offering.manufacturer": string
"service_offering.model_id": string
"service_offering.model_number": string
"service_offering.monitor": string
"service_offering.monitoring_requirements": string
"service_offering.name": string
"service_offering.number": string
"service_offering.operational_status": string
"service_offering.order": string
"service_offering.order_date": string
"service_offering.owned_by": string
"service_offering.parent": string
"service_offering.po_number": string
"service_offering.prerequisites": string
"service_offering.price": string
"service_offering.price_model": string
"service_offering.price_unit": string
"service_offering.purchase_date": string
"service_offering.schedule": string
"service_offering.serial_number": string
"service_offering.service_classification": string
"service_offering.service_level_requirement": string
"service_offering.short_description": string
"service_offering.skip_sync": string
"service_offering.sla": string
"service_offering.start_date": string
"service_offering.subcategory": string
"service_offering.supported_by": string
"service_offering.support_group": string
"service_offering.sys_class_name": string
"service_offering.sys_class_path": string
"service_offering.sys_created_by": string
"service_offering.sys_created_on": string
"service_offering.sys_domain": string
"service_offering.sys_domain_path": string
"service_offering.sys_id": string
"service_offering.sys_mod_count": string
"service_offering.sys_updated_by": string
"service_offering.sys_updated_on": string
"service_offering.technical_contact": string
"service_offering.unit_description": string
"service_offering.unverified": string
"service_offering.used_for": string
"service_offering.user_group": string
"service_offering.vendor": string
"service_offering.version": string
"service_offering.warranty_expiration": string;
      }
    }
   