declare interface sla {
      accountable_user: GlideElement<sla, glideElementType.g_reference<sys_user>>;
active: GlideElement<sla, glideElementType.g_boolean>;
avail_pct: GlideElement<sla, glideElementType.defaultType>;
begins: GlideElement<sla, glideElementType.g_glide_date>;
business_lead: GlideElement<sla, glideElementType.g_reference<sys_user>>;
business_unit: GlideElement<sla, glideElementType.defaultType>;
calendar: GlideElement<sla, glideElementType.g_reference<sys_calendar>>;
change_procedures: GlideElement<sla, glideElementType.defaultType>;
consultant_user: GlideElement<sla, glideElementType.g_reference<sys_user>>;
contract: GlideElement<sla, glideElementType.g_reference<ast_contract>>;
department: GlideElement<sla, glideElementType.g_reference<cmn_department>>;
description: GlideElement<sla, glideElementType.defaultType>;
disaster_recovery: GlideElement<sla, glideElementType.defaultType>;
ends: GlideElement<sla, glideElementType.g_glide_date>;
functional_area: GlideElement<sla, glideElementType.defaultType>;
incident_procedures: GlideElement<sla, glideElementType.defaultType>;
informed_user: GlideElement<sla, glideElementType.g_reference<sys_user>>;
maintenance: GlideElement<sla, glideElementType.g_reference<sys_calendar>>;
name: GlideElement<sla, glideElementType.defaultType>;
next_review: GlideElement<sla, glideElementType.g_glide_date>;
notes: GlideElement<sla, glideElementType.defaultType>;
number: GlideElement<sla, glideElementType.defaultType>;
reponsibilities: GlideElement<sla, glideElementType.defaultType>;
response_time: GlideElement<sla, glideElementType.defaultType>;
responsible_user: GlideElement<sla, glideElementType.g_reference<sys_user>>;
security_notes: GlideElement<sla, glideElementType.defaultType>;
service_goals: GlideElement<sla, glideElementType.defaultType>;
short_description: GlideElement<sla, glideElementType.defaultType>;
signatures: GlideElement<sla, glideElementType.defaultType>;
sys_class_name: GlideElement<sla, glideElementType.defaultType>;
sys_created_by: GlideElement<sla, glideElementType.defaultType>;
sys_created_on: GlideElement<sla, glideElementType.g_glide_date_time>;
sys_id: GlideElement<sla, glideElementType.defaultType>;
sys_mod_count: GlideElement<sla, glideElementType.defaultType>;
sys_updated_by: GlideElement<sla, glideElementType.defaultType>;
sys_updated_on: GlideElement<sla, glideElementType.g_glide_date_time>;
technical_lead: GlideElement<sla, glideElementType.g_reference<sys_user>>;
transaction_load: GlideElement<sla, glideElementType.defaultType>;
users: GlideElement<sla, glideElementType.g_reference<sys_user_group>>;
      _referenceKeys: never | {
        "accountable_user.accumulated_roles": string
"accountable_user.active": string
"accountable_user.avatar": string
"accountable_user.building": string
"accountable_user.calendar_integration": string
"accountable_user.city": string
"accountable_user.company": string
"accountable_user.cost_center": string
"accountable_user.country": string
"accountable_user.date_format": string
"accountable_user.default_perspective": string
"accountable_user.department": string
"accountable_user.email": string
"accountable_user.employee_number": string
"accountable_user.enable_multifactor_authn": string
"accountable_user.failed_attempts": string
"accountable_user.first_name": string
"accountable_user.gender": string
"accountable_user.home_phone": string
"accountable_user.internal_integration_user": string
"accountable_user.introduction": string
"accountable_user.last_login": string
"accountable_user.last_login_time": string
"accountable_user.last_name": string
"accountable_user.ldap_server": string
"accountable_user.location": string
"accountable_user.locked_out": string
"accountable_user.manager": string
"accountable_user.middle_name": string
"accountable_user.mobile_phone": string
"accountable_user.name": string
"accountable_user.notification": string
"accountable_user.password_needs_reset": string
"accountable_user.phone": string
"accountable_user.photo": string
"accountable_user.preferred_language": string
"accountable_user.roles": string
"accountable_user.schedule": string
"accountable_user.source": string
"accountable_user.state": string
"accountable_user.street": string
"accountable_user.sys_class_name": string
"accountable_user.sys_created_by": string
"accountable_user.sys_created_on": string
"accountable_user.sys_domain": string
"accountable_user.sys_domain_path": string
"accountable_user.sys_id": string
"accountable_user.sys_mod_count": string
"accountable_user.sys_updated_by": string
"accountable_user.sys_updated_on": string
"accountable_user.time_format": string
"accountable_user.time_zone": string
"accountable_user.title": string
"accountable_user.user_name": string
"accountable_user.user_password": string
"accountable_user.vip": string
"accountable_user.web_service_access_only": string
"accountable_user.zip": string
"business_lead.accumulated_roles": string
"business_lead.active": string
"business_lead.avatar": string
"business_lead.building": string
"business_lead.calendar_integration": string
"business_lead.city": string
"business_lead.company": string
"business_lead.cost_center": string
"business_lead.country": string
"business_lead.date_format": string
"business_lead.default_perspective": string
"business_lead.department": string
"business_lead.email": string
"business_lead.employee_number": string
"business_lead.enable_multifactor_authn": string
"business_lead.failed_attempts": string
"business_lead.first_name": string
"business_lead.gender": string
"business_lead.home_phone": string
"business_lead.internal_integration_user": string
"business_lead.introduction": string
"business_lead.last_login": string
"business_lead.last_login_time": string
"business_lead.last_name": string
"business_lead.ldap_server": string
"business_lead.location": string
"business_lead.locked_out": string
"business_lead.manager": string
"business_lead.middle_name": string
"business_lead.mobile_phone": string
"business_lead.name": string
"business_lead.notification": string
"business_lead.password_needs_reset": string
"business_lead.phone": string
"business_lead.photo": string
"business_lead.preferred_language": string
"business_lead.roles": string
"business_lead.schedule": string
"business_lead.source": string
"business_lead.state": string
"business_lead.street": string
"business_lead.sys_class_name": string
"business_lead.sys_created_by": string
"business_lead.sys_created_on": string
"business_lead.sys_domain": string
"business_lead.sys_domain_path": string
"business_lead.sys_id": string
"business_lead.sys_mod_count": string
"business_lead.sys_updated_by": string
"business_lead.sys_updated_on": string
"business_lead.time_format": string
"business_lead.time_zone": string
"business_lead.title": string
"business_lead.user_name": string
"business_lead.user_password": string
"business_lead.vip": string
"business_lead.web_service_access_only": string
"business_lead.zip": string
"calendar.name": string
"calendar.sys_id": string
"calendar.sys_class_name": string
"calendar.sys_created_by": string
"calendar.sys_created_on": string
"calendar.sys_mod_count": string
"calendar.sys_name": string
"calendar.sys_package": string
"calendar.sys_policy": string
"calendar.sys_scope": string
"calendar.sys_updated_by": string
"calendar.sys_updated_on": string
"calendar.sys_update_name": string
"consultant_user.accumulated_roles": string
"consultant_user.active": string
"consultant_user.avatar": string
"consultant_user.building": string
"consultant_user.calendar_integration": string
"consultant_user.city": string
"consultant_user.company": string
"consultant_user.cost_center": string
"consultant_user.country": string
"consultant_user.date_format": string
"consultant_user.default_perspective": string
"consultant_user.department": string
"consultant_user.email": string
"consultant_user.employee_number": string
"consultant_user.enable_multifactor_authn": string
"consultant_user.failed_attempts": string
"consultant_user.first_name": string
"consultant_user.gender": string
"consultant_user.home_phone": string
"consultant_user.internal_integration_user": string
"consultant_user.introduction": string
"consultant_user.last_login": string
"consultant_user.last_login_time": string
"consultant_user.last_name": string
"consultant_user.ldap_server": string
"consultant_user.location": string
"consultant_user.locked_out": string
"consultant_user.manager": string
"consultant_user.middle_name": string
"consultant_user.mobile_phone": string
"consultant_user.name": string
"consultant_user.notification": string
"consultant_user.password_needs_reset": string
"consultant_user.phone": string
"consultant_user.photo": string
"consultant_user.preferred_language": string
"consultant_user.roles": string
"consultant_user.schedule": string
"consultant_user.source": string
"consultant_user.state": string
"consultant_user.street": string
"consultant_user.sys_class_name": string
"consultant_user.sys_created_by": string
"consultant_user.sys_created_on": string
"consultant_user.sys_domain": string
"consultant_user.sys_domain_path": string
"consultant_user.sys_id": string
"consultant_user.sys_mod_count": string
"consultant_user.sys_updated_by": string
"consultant_user.sys_updated_on": string
"consultant_user.time_format": string
"consultant_user.time_zone": string
"consultant_user.title": string
"consultant_user.user_name": string
"consultant_user.user_password": string
"consultant_user.vip": string
"consultant_user.web_service_access_only": string
"consultant_user.zip": string
"contract.active": string
"contract.applicable_taxes": string
"contract.application_model": string
"contract.approval_history": string
"contract.approver": string
"contract.business_owner": string
"contract.commitment": string
"contract.contract_administrator": string
"contract.contract_model": string
"contract.cost_adjustment": string
"contract.cost_adjustment_percentage": string
"contract.cost_adjustment_reason": string
"contract.cost_adjustment_type": string
"contract.cost_center": string
"contract.cost_per_unit": string
"contract.covers": string
"contract.customer": string
"contract.description": string
"contract.discount": string
"contract.ends": string
"contract.expiration": string
"contract.invoice_payment_terms": string
"contract.license_quantity_entitled": string
"contract.license_type": string
"contract.lifetime_cost": string
"contract.location": string
"contract.monthly_cost": string
"contract.number": string
"contract.parent_contract": string
"contract.payment_amount": string
"contract.payment_schedule": string
"contract.po_number": string
"contract.process": string
"contract.process_non_contractual_slas": string
"contract.ratecard": string
"contract.renewable": string
"contract.renewal_contact": string
"contract.renewal_date": string
"contract.renewal_end_date": string
"contract.renewal_options": string
"contract.sales_tax": string
"contract.short_description": string
"contract.starts": string
"contract.state": string
"contract.substate": string
"contract.sub_total_cost": string
"contract.sys_class_name": string
"contract.sys_created_by": string
"contract.sys_created_on": string
"contract.sys_domain": string
"contract.sys_domain_path": string
"contract.sys_id": string
"contract.sys_mod_count": string
"contract.sys_updated_by": string
"contract.sys_updated_on": string
"contract.tax_cost": string
"contract.tax_exempt": string
"contract.tax_rate": string
"contract.terms_and_conditions": string
"contract.total_cost": string
"contract.vendor": string
"contract.vendor_account": string
"contract.vendor_contract": string
"contract.yearly_cost": string
"department.business_unit": string
"department.company": string
"department.cost_center": string
"department.dept_head": string
"department.description": string
"department.head_count": string
"department.id": string
"department.name": string
"department.parent": string
"department.primary_contact": string
"department.sys_created_by": string
"department.sys_created_on": string
"department.sys_id": string
"department.sys_mod_count": string
"department.sys_updated_by": string
"department.sys_updated_on": string
"informed_user.accumulated_roles": string
"informed_user.active": string
"informed_user.avatar": string
"informed_user.building": string
"informed_user.calendar_integration": string
"informed_user.city": string
"informed_user.company": string
"informed_user.cost_center": string
"informed_user.country": string
"informed_user.date_format": string
"informed_user.default_perspective": string
"informed_user.department": string
"informed_user.email": string
"informed_user.employee_number": string
"informed_user.enable_multifactor_authn": string
"informed_user.failed_attempts": string
"informed_user.first_name": string
"informed_user.gender": string
"informed_user.home_phone": string
"informed_user.internal_integration_user": string
"informed_user.introduction": string
"informed_user.last_login": string
"informed_user.last_login_time": string
"informed_user.last_name": string
"informed_user.ldap_server": string
"informed_user.location": string
"informed_user.locked_out": string
"informed_user.manager": string
"informed_user.middle_name": string
"informed_user.mobile_phone": string
"informed_user.name": string
"informed_user.notification": string
"informed_user.password_needs_reset": string
"informed_user.phone": string
"informed_user.photo": string
"informed_user.preferred_language": string
"informed_user.roles": string
"informed_user.schedule": string
"informed_user.source": string
"informed_user.state": string
"informed_user.street": string
"informed_user.sys_class_name": string
"informed_user.sys_created_by": string
"informed_user.sys_created_on": string
"informed_user.sys_domain": string
"informed_user.sys_domain_path": string
"informed_user.sys_id": string
"informed_user.sys_mod_count": string
"informed_user.sys_updated_by": string
"informed_user.sys_updated_on": string
"informed_user.time_format": string
"informed_user.time_zone": string
"informed_user.title": string
"informed_user.user_name": string
"informed_user.user_password": string
"informed_user.vip": string
"informed_user.web_service_access_only": string
"informed_user.zip": string
"maintenance.name": string
"maintenance.sys_id": string
"maintenance.sys_class_name": string
"maintenance.sys_created_by": string
"maintenance.sys_created_on": string
"maintenance.sys_mod_count": string
"maintenance.sys_name": string
"maintenance.sys_package": string
"maintenance.sys_policy": string
"maintenance.sys_scope": string
"maintenance.sys_updated_by": string
"maintenance.sys_updated_on": string
"maintenance.sys_update_name": string
"responsible_user.accumulated_roles": string
"responsible_user.active": string
"responsible_user.avatar": string
"responsible_user.building": string
"responsible_user.calendar_integration": string
"responsible_user.city": string
"responsible_user.company": string
"responsible_user.cost_center": string
"responsible_user.country": string
"responsible_user.date_format": string
"responsible_user.default_perspective": string
"responsible_user.department": string
"responsible_user.email": string
"responsible_user.employee_number": string
"responsible_user.enable_multifactor_authn": string
"responsible_user.failed_attempts": string
"responsible_user.first_name": string
"responsible_user.gender": string
"responsible_user.home_phone": string
"responsible_user.internal_integration_user": string
"responsible_user.introduction": string
"responsible_user.last_login": string
"responsible_user.last_login_time": string
"responsible_user.last_name": string
"responsible_user.ldap_server": string
"responsible_user.location": string
"responsible_user.locked_out": string
"responsible_user.manager": string
"responsible_user.middle_name": string
"responsible_user.mobile_phone": string
"responsible_user.name": string
"responsible_user.notification": string
"responsible_user.password_needs_reset": string
"responsible_user.phone": string
"responsible_user.photo": string
"responsible_user.preferred_language": string
"responsible_user.roles": string
"responsible_user.schedule": string
"responsible_user.source": string
"responsible_user.state": string
"responsible_user.street": string
"responsible_user.sys_class_name": string
"responsible_user.sys_created_by": string
"responsible_user.sys_created_on": string
"responsible_user.sys_domain": string
"responsible_user.sys_domain_path": string
"responsible_user.sys_id": string
"responsible_user.sys_mod_count": string
"responsible_user.sys_updated_by": string
"responsible_user.sys_updated_on": string
"responsible_user.time_format": string
"responsible_user.time_zone": string
"responsible_user.title": string
"responsible_user.user_name": string
"responsible_user.user_password": string
"responsible_user.vip": string
"responsible_user.web_service_access_only": string
"responsible_user.zip": string
"technical_lead.accumulated_roles": string
"technical_lead.active": string
"technical_lead.avatar": string
"technical_lead.building": string
"technical_lead.calendar_integration": string
"technical_lead.city": string
"technical_lead.company": string
"technical_lead.cost_center": string
"technical_lead.country": string
"technical_lead.date_format": string
"technical_lead.default_perspective": string
"technical_lead.department": string
"technical_lead.email": string
"technical_lead.employee_number": string
"technical_lead.enable_multifactor_authn": string
"technical_lead.failed_attempts": string
"technical_lead.first_name": string
"technical_lead.gender": string
"technical_lead.home_phone": string
"technical_lead.internal_integration_user": string
"technical_lead.introduction": string
"technical_lead.last_login": string
"technical_lead.last_login_time": string
"technical_lead.last_name": string
"technical_lead.ldap_server": string
"technical_lead.location": string
"technical_lead.locked_out": string
"technical_lead.manager": string
"technical_lead.middle_name": string
"technical_lead.mobile_phone": string
"technical_lead.name": string
"technical_lead.notification": string
"technical_lead.password_needs_reset": string
"technical_lead.phone": string
"technical_lead.photo": string
"technical_lead.preferred_language": string
"technical_lead.roles": string
"technical_lead.schedule": string
"technical_lead.source": string
"technical_lead.state": string
"technical_lead.street": string
"technical_lead.sys_class_name": string
"technical_lead.sys_created_by": string
"technical_lead.sys_created_on": string
"technical_lead.sys_domain": string
"technical_lead.sys_domain_path": string
"technical_lead.sys_id": string
"technical_lead.sys_mod_count": string
"technical_lead.sys_updated_by": string
"technical_lead.sys_updated_on": string
"technical_lead.time_format": string
"technical_lead.time_zone": string
"technical_lead.title": string
"technical_lead.user_name": string
"technical_lead.user_password": string
"technical_lead.vip": string
"technical_lead.web_service_access_only": string
"technical_lead.zip": string
"users.active": string
"users.cost_center": string
"users.default_assignee": string
"users.description": string
"users.email": string
"users.exclude_manager": string
"users.include_members": string
"users.manager": string
"users.name": string
"users.parent": string
"users.roles": string
"users.source": string
"users.sys_created_by": string
"users.sys_created_on": string
"users.sys_id": string
"users.sys_mod_count": string
"users.sys_updated_by": string
"users.sys_updated_on": string
"users.type": string;
      }
    }
   