declare interface sys_app_module {
      active: GlideElement<sys_app_module, glideElementType.g_boolean>;
application: GlideElement<sys_app_module, glideElementType.g_reference<sys_app_application>>;
assessment: GlideElement<sys_app_module, glideElementType.g_reference<asmt_metric_type>>;
device_type: GlideElement<sys_app_module, glideElementType.defaultType>;
filter: GlideElement<sys_app_module, glideElementType.defaultType>;
hint: GlideElement<sys_app_module, glideElementType.defaultType>;
homepage: GlideElement<sys_app_module, glideElementType.g_reference<sys_portal_page>>;
image: GlideElement<sys_app_module, glideElementType.defaultType>;
link_type: GlideElement<sys_app_module, glideElementType.defaultType>;
map_page: GlideElement<sys_app_module, glideElementType.g_reference<cmn_map_page>>;
mobile_title: GlideElement<sys_app_module, glideElementType.defaultType>;
mobile_view_name: GlideElement<sys_app_module, glideElementType.defaultType>;
name: GlideElement<sys_app_module, glideElementType.defaultType>;
order: GlideElement<sys_app_module, glideElementType.defaultType>;
override_menu_roles: GlideElement<sys_app_module, glideElementType.g_boolean>;
query: GlideElement<sys_app_module, glideElementType.defaultType>;
report: GlideElement<sys_app_module, glideElementType.g_reference<sys_report>>;
roles: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_domain: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_domain_path: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_id: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_overrides: GlideElement<sys_app_module, glideElementType.g_reference<sys_app_module>>;
timeline_page: GlideElement<sys_app_module, glideElementType.g_reference<cmn_timeline_page>>;
title: GlideElement<sys_app_module, glideElementType.defaultType>;
uncancelable: GlideElement<sys_app_module, glideElementType.g_boolean>;
view_name: GlideElement<sys_app_module, glideElementType.defaultType>;
window_name: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_class_name: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_created_by: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_created_on: GlideElement<sys_app_module, glideElementType.g_glide_date_time>;
sys_mod_count: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_name: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_package: GlideElement<sys_app_module, glideElementType.g_reference<sys_package>>;
sys_policy: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_scope: GlideElement<sys_app_module, glideElementType.g_reference<sys_scope>>;
sys_updated_by: GlideElement<sys_app_module, glideElementType.defaultType>;
sys_updated_on: GlideElement<sys_app_module, glideElementType.g_glide_date_time>;
sys_update_name: GlideElement<sys_app_module, glideElementType.defaultType>;
      _referenceKeys: never | {
        "application.active": string
"application.category": string
"application.description": string
"application.device_type": string
"application.hint": string
"application.name": string
"application.order": string
"application.roles": string
"application.sys_domain": string
"application.sys_domain_path": string
"application.sys_id": string
"application.sys_overrides": string
"application.title": string
"application.view_name": string
"application.sys_class_name": string
"application.sys_created_by": string
"application.sys_created_on": string
"application.sys_mod_count": string
"application.sys_name": string
"application.sys_package": string
"application.sys_policy": string
"application.sys_scope": string
"application.sys_updated_by": string
"application.sys_updated_on": string
"application.sys_update_name": string
"assessment.active": string
"assessment.allow_public": string
"assessment.allow_retake": string
"assessment.anonymize": string
"assessment.business_rule": string
"assessment.condition": string
"assessment.default_filter": string
"assessment.delete_business_rule": string
"assessment.description": string
"assessment.disable_ui_action": string
"assessment.display_all_filters": string
"assessment.display_field": string
"assessment.duration": string
"assessment.enable_ui_action": string
"assessment.end_note": string
"assessment.enforce_condition": string
"assessment.evaluation_method": string
"assessment.filter_condition": string
"assessment.filter_table": string
"assessment.introduction": string
"assessment.job": string
"assessment.live_feed": string
"assessment.name": string
"assessment.notify_if_overdue": string
"assessment.notify_user": string
"assessment.not_show_intro_note": string
"assessment.one_click_survey": string
"assessment.overdue_notify_user": string
"assessment.portal_pagination": string
"assessment.publish_state": string
"assessment.roles": string
"assessment.sample_metric": string
"assessment.scale_factor": string
"assessment.schedule_period": string
"assessment.schedule_type": string
"assessment.scoring_type": string
"assessment.signature": string
"assessment.source_table": string
"assessment.survey_owners": string
"assessment.sys_domain": string
"assessment.sys_domain_path": string
"assessment.sys_id": string
"assessment.table": string
"assessment.url": string
"assessment.user_field": string
"assessment.sys_class_name": string
"assessment.sys_created_by": string
"assessment.sys_created_on": string
"assessment.sys_mod_count": string
"assessment.sys_name": string
"assessment.sys_package": string
"assessment.sys_policy": string
"assessment.sys_scope": string
"assessment.sys_updated_by": string
"assessment.sys_updated_on": string
"assessment.sys_update_name": string
"homepage.layout": string
"homepage.order": string
"homepage.read_roles": string
"homepage.roles": string
"homepage.selectable": string
"homepage.sys_domain": string
"homepage.sys_domain_path": string
"homepage.sys_id": string
"homepage.sys_overrides": string
"homepage.title": string
"homepage.user": string
"homepage.view": string
"homepage.sys_class_name": string
"homepage.sys_created_by": string
"homepage.sys_created_on": string
"homepage.sys_mod_count": string
"homepage.sys_name": string
"homepage.sys_package": string
"homepage.sys_policy": string
"homepage.sys_scope": string
"homepage.sys_updated_by": string
"homepage.sys_updated_on": string
"homepage.sys_update_name": string
"map_page.center_address": string
"map_page.center_latitude": string
"map_page.center_longitude": string
"map_page.controls_size": string
"map_page.initial_zoom": string
"map_page.name": string
"map_page.overview": string
"map_page.refresh_on_zoom": string
"map_page.script": string
"map_page.show_device_location": string
"map_page.suffix": string
"map_page.sys_id": string
"map_page.type": string
"map_page.type_selection": string
"map_page.sys_class_name": string
"map_page.sys_created_by": string
"map_page.sys_created_on": string
"map_page.sys_mod_count": string
"map_page.sys_name": string
"map_page.sys_package": string
"map_page.sys_policy": string
"map_page.sys_scope": string
"map_page.sys_updated_by": string
"map_page.sys_updated_on": string
"map_page.sys_update_name": string
"report.additional_groupby": string
"report.aggregate": string
"report.allow_data_label_overlap": string
"report.axis_max_color": string
"report.axis_min_color": string
"report.bar_unstack": string
"report.chart_background_color": string
"report.chart_border_color": string
"report.chart_border_radius": string
"report.chart_border_width": string
"report.chart_height": string
"report.chart_size": string
"report.chart_subtitle": string
"report.chart_subtitle_color": string
"report.chart_subtitle_size": string
"report.chart_subtitle_style": string
"report.chart_title": string
"report.chart_title_color": string
"report.chart_title_size": string
"report.chart_title_style": string
"report.chart_title_x_position": string
"report.chart_title_y_position": string
"report.chart_width": string
"report.color": string
"report.colors": string
"report.color_palette": string
"report.column": string
"report.compute_percent": string
"report.content": string
"report.created_by_user": string
"report.custom_chart_size": string
"report.custom_chart_title_position": string
"report.custom_config": string
"report.decimal_precision": string
"report.description": string
"report.direction": string
"report.display_column_lines": string
"report.display_grid": string
"report.display_row_lines": string
"report.donut_width_percent": string
"report.end_time": string
"report.exp_report_attrs": string
"report.field": string
"report.field_list": string
"report.filter": string
"report.from": string
"report.funnel_neck_percent": string
"report.gauge_autoscale": string
"report.group": string
"report.import_table": string
"report.interval": string
"report.is_published": string
"report.is_real_time": string
"report.is_scheduled": string
"report.legend_align_columns": string
"report.legend_background_color": string
"report.legend_border_color": string
"report.legend_border_radius": string
"report.legend_border_width": string
"report.legend_horizontal_alignment": string
"report.legend_items_left_align": string
"report.legend_vertical_alignment": string
"report.list_ui_view": string
"report.location_field": string
"report.lower_limit": string
"report.map": string
"report.map_source": string
"report.orderby_list": string
"report.others": string
"report.other_threshold": string
"report.page_hdrftr": string
"report.pivot_expanded": string
"report.report_drilldown": string
"report.report_source": string
"report.roles": string
"report.row": string
"report.score_color": string
"report.sc_groupby_item_id": string
"report.sc_groupby_variable_id": string
"report.sc_stackby_item_id": string
"report.sc_stackby_variable_id": string
"report.series_name_text": string
"report.set_color": string
"report.show_chart_border": string
"report.show_chart_data_label": string
"report.show_chart_title": string
"report.show_chart_total": string
"report.show_data_label_position_middle": string
"report.show_empty": string
"report.show_geographical_label": string
"report.show_legend": string
"report.show_legend_border": string
"report.show_marker": string
"report.show_zero": string
"report.source_type": string
"report.start_time": string
"report.style_config": string
"report.sumfield": string
"report.sys_id": string
"report.table": string
"report.title": string
"report.title_horizontal_alignment": string
"report.title_vertical_alignment": string
"report.to": string
"report.trend_field": string
"report.type": string
"report.upper_limit": string
"report.user": string
"report.use_color_heatmap": string
"report.use_null_in_trend": string
"report.x_axis_allow_decimals": string
"report.x_axis_display_grid": string
"report.x_axis_grid_color": string
"report.x_axis_grid_dotted": string
"report.x_axis_grid_width": string
"report.x_axis_label_bold": string
"report.x_axis_label_color": string
"report.x_axis_label_size": string
"report.x_axis_label_tilt": string
"report.x_axis_opposite": string
"report.x_axis_title": string
"report.x_axis_title_bold": string
"report.x_axis_title_color": string
"report.x_axis_title_size": string
"report.y_axis_allow_decimals": string
"report.y_axis_display_grid": string
"report.y_axis_from": string
"report.y_axis_grid_color": string
"report.y_axis_grid_dotted": string
"report.y_axis_grid_width": string
"report.y_axis_label_bold": string
"report.y_axis_label_color": string
"report.y_axis_label_size": string
"report.y_axis_label_tilt": string
"report.y_axis_opposite": string
"report.y_axis_title": string
"report.y_axis_title_bold": string
"report.y_axis_title_color": string
"report.y_axis_title_size": string
"report.y_axis_to": string
"report.sys_class_name": string
"report.sys_created_by": string
"report.sys_created_on": string
"report.sys_mod_count": string
"report.sys_name": string
"report.sys_package": string
"report.sys_policy": string
"report.sys_scope": string
"report.sys_updated_by": string
"report.sys_updated_on": string
"report.sys_update_name": string
"sys_overrides.active": string
"sys_overrides.application": string
"sys_overrides.assessment": string
"sys_overrides.device_type": string
"sys_overrides.filter": string
"sys_overrides.hint": string
"sys_overrides.homepage": string
"sys_overrides.image": string
"sys_overrides.link_type": string
"sys_overrides.map_page": string
"sys_overrides.mobile_title": string
"sys_overrides.mobile_view_name": string
"sys_overrides.name": string
"sys_overrides.order": string
"sys_overrides.override_menu_roles": string
"sys_overrides.query": string
"sys_overrides.report": string
"sys_overrides.roles": string
"sys_overrides.sys_domain": string
"sys_overrides.sys_domain_path": string
"sys_overrides.sys_id": string
"sys_overrides.sys_overrides": string
"sys_overrides.timeline_page": string
"sys_overrides.title": string
"sys_overrides.uncancelable": string
"sys_overrides.view_name": string
"sys_overrides.window_name": string
"sys_overrides.sys_class_name": string
"sys_overrides.sys_created_by": string
"sys_overrides.sys_created_on": string
"sys_overrides.sys_mod_count": string
"sys_overrides.sys_name": string
"sys_overrides.sys_package": string
"sys_overrides.sys_policy": string
"sys_overrides.sys_scope": string
"sys_overrides.sys_updated_by": string
"sys_overrides.sys_updated_on": string
"sys_overrides.sys_update_name": string
"timeline_page.allow_dragging": string
"timeline_page.allow_drag_left": string
"timeline_page.allow_drag_right": string
"timeline_page.auto_refresh": string
"timeline_page.condition": string
"timeline_page.css_span_color": string
"timeline_page.end_date_field": string
"timeline_page.labels": string
"timeline_page.name": string
"timeline_page.perform_custom_sort": string
"timeline_page.range_calculator": string
"timeline_page.show_grid_lines": string
"timeline_page.show_left_pane": string
"timeline_page.show_span_text": string
"timeline_page.show_summary_pane": string
"timeline_page.show_tooltips": string
"timeline_page.sort_by": string
"timeline_page.sort_by_order": string
"timeline_page.start_date_field": string
"timeline_page.suffix": string
"timeline_page.sys_id": string
"timeline_page.table": string
"timeline_page.tooltip_label": string
"timeline_page.sys_class_name": string
"timeline_page.sys_created_by": string
"timeline_page.sys_created_on": string
"timeline_page.sys_mod_count": string
"timeline_page.sys_name": string
"timeline_page.sys_package": string
"timeline_page.sys_policy": string
"timeline_page.sys_scope": string
"timeline_page.sys_updated_by": string
"timeline_page.sys_updated_on": string
"timeline_page.sys_update_name": string
"sys_package.active": string
"sys_package.enforce_license": string
"sys_package.licensable": string
"sys_package.license_category": string
"sys_package.license_model": string
"sys_package.name": string
"sys_package.source": string
"sys_package.sys_class_name": string
"sys_package.sys_created_by": string
"sys_package.sys_created_on": string
"sys_package.sys_id": string
"sys_package.sys_mod_count": string
"sys_package.sys_updated_by": string
"sys_package.sys_updated_on": string
"sys_package.trackable": string
"sys_package.version": string
"sys_scope.can_edit_in_studio": string
"sys_scope.guided_setup_guid": string
"sys_scope.js_level": string
"sys_scope.logo": string
"sys_scope.private": string
"sys_scope.restrict_table_access": string
"sys_scope.runtime_access_tracking": string
"sys_scope.scope": string
"sys_scope.scoped_administration": string
"sys_scope.short_description": string
"sys_scope.sys_id": string
"sys_scope.template": string
"sys_scope.vendor": string
"sys_scope.vendor_prefix": string
"sys_scope.active": string
"sys_scope.enforce_license": string
"sys_scope.licensable": string
"sys_scope.license_category": string
"sys_scope.license_model": string
"sys_scope.name": string
"sys_scope.source": string
"sys_scope.sys_class_name": string
"sys_scope.sys_created_by": string
"sys_scope.sys_created_on": string
"sys_scope.sys_mod_count": string
"sys_scope.sys_updated_by": string
"sys_scope.sys_updated_on": string
"sys_scope.trackable": string
"sys_scope.version": string;
      }
    }
   